### ISSUE TITLE
Add YousList to the list of known subscriptions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#10]
@yous commented on [Tue Nov 21 2017](https://github.com/AdguardTeam/AdguardFilters/issues/7784)

Hi, I'm an author of [YousList](https://github.com/yous/YousList), which is a Korean adblock filter. It's mainly for Korean websites, but I'm trying to make this work globally. The URL of the filter is <https://github.com/yous/YousList/raw/master/youslist.txt>.

This filter has 4,152 items and keeps on updating. It's compatible with Adblock Plus 2.0 rules, and added to [uBlock](https://github.com/gorhill/uBlock/pull/1029) and [Adblock Plus](https://adblockplus.org/subscriptions) filter list.

I couldn't find some guides for adding a filter to this project, so if I did something wrong, please let me know.

---

@ameshkov commented on [Tue Nov 21 2017](https://github.com/AdguardTeam/AdguardFilters/issues/7784#issuecomment-346020270)

Hey! You did everything right, thank you! Adding a new filter to the list of available may take some time, but we will definitely do it.

**Comment by Alex-302** [comment]
added

**Comment by yous** [comment]
Thank you!

**Comment by akmLaVx** [comment]
The list seems to still be unavailable in our Safari extension. It is clearly available in other exts (Chrome, Edge, FIrefox, etc)

**Comment by yous** [comment]
I also got a mention that the list is unavailable on the Android version. https://github.com/yous/YousList/issues/47

**Comment by ameshkov** [comment]
Hi @yous, thank you for mentioning it!

In some apps updating a list of known filters subscriptions requires an app update.

* Browser extension: it will be available in the next update of Safari extension (already available in Chrome/FF).
* Android apps: my bad, we'll include it in the next update: 
    https://github.com/AdguardTeam/AdguardForAndroid/issues/1803
    https://github.com/AdguardTeam/ContentBlocker/issues/113

**Comment by yous** [comment]
@ameshkov, thank you for the quick response!
