### ISSUE TITLE
Add `Polish GDPR-Cookies Filters` to v5

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersRegistry#1015]
### Issue Details

Polish GDPR-Cookies Filters is popular Polish filter.
~5200 rules.

### Proposed solution

Add this filter.

**Comment by krystian3w** [comment]
I would also rather ask for support in dramatic cases: https://github.com/AdguardTeam/FiltersRegistry/pull/994#issuecomment-2315768898 (unless the problem overwhelms the entire community).

**Comment by Alex-302** [comment]
@krystian3w Did not get. Whose support for whom?:)

**Comment by krystian3w** [comment]
As I will outgrow the repair of cookie-cutting specific to MV3.
