### ISSUE TITLE
`filters.adtidy.org` returns HTTP 200 even when `If-None-Match` matches server `ETag`

### ISSUE THREAD

**Issue by SukkaW** [AdguardTeam/FiltersRegistry#1025]
### Prerequisites

- [X] This problem is not related to filtering issues. Otherwise, you should read this [article](https://kb.adguard.com/technical-support/reporting-tool);
- [X] You're using an up-to-date version of the problematic filter;

### Problem description

I regularly fetch AdGuard's filter from `filters.adtidy.org`. To avoid overloading AdGuard's server/CDN, I've implemented a cache based on `ETag`. However, I've noticed that `filters.adtidy.org` sometimes returns HTTP 200 instead of HTTP 304, even when the returned `ETag` matches the sent `If-None-Match`:

<img width="699" alt="image" src="https://github.com/user-attachments/assets/3b2aa7e3-2d39-4776-875c-62456d7c2071">
<img width="862" alt="image" src="https://github.com/user-attachments/assets/04bd6c52-3680-4ab9-bb01-1a8efefd1304">

This behavior cannot be reproduced consistently, though:

<img width="757" alt="image" src="https://github.com/user-attachments/assets/144c80ca-66b5-4ce9-99e4-0722613522d3">

### Proposed solution

Check the implementation of AdGuard's registry server and the CDN provider (CDN77) to make sure always returns HTTP 304 when the server `ETag` matches `If-None-Match`.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@SukkaW But 

> To avoid overloading AdGuard's server/CDN, I've implemented a cache based on `ETag`

Do you have many clients? One user usually is not a problem for servers)
Also our filters support diff-update
https://filters.adtidy.org/extension/chromium/patches/18/18-s-1729265794-3600.patch
https://github.com/AdguardTeam/FiltersCompiler/issues/192

**Comment by D13410N3** [comment]
Hello. 
Unfortunately it is not possible right now due to some filters update implementation reasons.
