### ISSUE TITLE
Legitimate site blocked:

### ISSUE THREAD

**Issue by techyguyperplexable** [AdguardTeam/FiltersRegistry#1036]
### Prerequisites

- [X] This problem is not related to filtering issues. Otherwise, you should read this [article](https://kb.adguard.com/technical-support/reporting-tool);
- [X] You're using an up-to-date version of the problematic filter;

### Problem description

I work with spoo.me as a security expert and I heard that this website is in a spam/blacklist,
Spoo.me is not a spam or scam, spoo.me is a url shortener, if you have any spam/scam urls you can report it. If you want to contact me personally then dm me at : objectfigure

Or the owner: zingzy

### Proposed solution

Remove spoo.me as a blocked URL

### Privacy

- [x] I agree to follow this condition

**Comment by zloyden** [comment]
> spoo.me is a url shortener

Hi! I see that, but we do not block the website. However, this is the wrong repo to address such issues. Please contact support@adguard.com in the future.
