### ISSUE TITLE
Add the filter I sentAdd the filter I sent

### ISSUE THREAD

**Issue by kolinrno** [AdguardTeam/FiltersRegistry#1037]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

The abp indo you provided has very few rules, so I think... you should replace it🙏🏻

### Proposed solution

My solution that I gave was to replace it with the ABP Indo filter too but with more rules too, actually there is no need to replace it, just add the filter that I gave below,,
https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt 

### Additional information

Let me know if this filter has been added. I use google translate to communicate with you

**Comment by zloyden** [comment]
Hi! As I see, there is no difference with the current `subscriptionUrl` of `ABPindo`. We only use sources provided by its authors.
