### ISSUE TITLE
[enhancement] alleblock.pl

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#11]
@FadeMind commented on [Thu Nov 02 2017](https://github.com/AdguardTeam/AdguardFilters/issues/7351)

Please consider adding AlleBlock rules to Adguard For Windows/Adguard For Android Filters List. 

https://github.com/maciejtarmas/AlleBlock

RAW file:  https://raw.githubusercontent.com/maciejtarmas/AlleBlock/master/alleblock.txt
`AlleBlock - Remove annoying elements from polish e-commerce sites`

**Comment by Alex-302** [comment]
added
