### ISSUE TITLE
Unsupported rules in iOS and Safari filters

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersRegistry#121]
* iOS
`$network`
`$empty` / `,empty`
`$csp=`
`$webrtc`
* Safari
`$empty` / `,empty`
`$webrtc`

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/FiltersCompiler #28](https://github.com/AdguardTeam/FiltersCompiler/issues/28) via [**ZenHub**](https://www.zenhub.com/)
