### ISSUE TITLE
Missed language tags in Ru AdList

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersRegistry#143]
https://github.com/AdguardTeam/AdguardForAndroid/issues/2386
https://github.com/AdguardTeam/FiltersRegistry/pull/144

**Comment by lancelot-moon** [comment]
ABPindo also has no language tag.
Thanks.

**Comment by Alex-302** [comment]
It has lang tag. This is a different issue.

**Comment by lancelot-moon** [comment]
But AG team wrongly used the description of Indonesian language-specific ad blocking  for Bulgarian (bg) label.

Just a remind.
Please don't mind.
