### ISSUE TITLE
Add List-KR

### ISSUE THREAD

**Issue by ptrkr** [AdguardTeam/FiltersRegistry#151]
[List-KR](https://github.com/List-KR/List-KR) is a web filter for websites in Korean language. This filter aims to filter not only ads, but also known trackers and other scripts which negatively affects user experience. SlowMemory, a original contributor, has deleted all his projects suddenly. As a result, Old List-KR filter have obsoleted in AdGuard configuration UI. So i have recreated this project repository for continued development.

Would you please add this list so it is available in the AdGuard configuration UI and can be enabled by users via a checkbox in the usual filter selection settings screen, and remove '(Obsolete) List-KR' filter?

**Comment by Alex-302** [comment]
It is not original filter: ` so i have recreated this project repository for continued development.`
Please watch it some time.

**Comment by ameshkov** [comment]
@ptrkr thank you for the contribution!

I'll set a reminder and will check it in 14 days to see if this subscription is actively developed.

**Comment by ptrkr** [comment]
@ameshkov hello

**Comment by ameshkov** [comment]
@ptrkr I remember:) I'll get back to it on Monday

**Comment by ptrkr** [comment]
@ameshkov Sorry for duplicate mention, but.. is anyone there?

**Comment by ameshkov** [comment]
Yep, all good. @Alex-302 let's replace the obsolete List-KR then.

**Comment by ameshkov** [comment]
@ptrkr there's one issue, though. The original `List-KR` used JS and `$replace` rules which we do not generally allow to third-party filters (we made a one-time exception for SlowMemory).

Please wait till we add scriptlets support: https://github.com/AdguardTeam/CoreLibs/issues/664

Meanwhile, if these rules are strictly necessary, please pull-request them directly to https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_227_List-KR/template.txt

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/FiltersRegistry/pull/155

**Comment by ptrkr** [comment]
@ameshkov @Alex-302 Thanks for answer! But i have a problem with filter subscription that '(Obsolute) List-KR' is still displayed in the subscription list like this:
![cap-0084](https://user-images.githubusercontent.com/27128153/51579846-c7450e80-1f05-11e9-9fdf-3d698071b354.png)
And when i visit korean websites which have web-advertisements, the filter doesn't seem to be automatically activated. I think it's because YousList is set as the default korean filter.. what can i do for resolve this problem?
