### ISSUE TITLE
Make the default whitelist for only DNS filtering.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/FiltersRegistry#153]
@ameshkov
@AdamWr

The new filter (whitelist) is only for DNS filtering, **NOT** for HTTPS filtering.

When users who enable DNS filtering meet incorrect blocking or anti-adblock, let them enable the default whitelist and take the risk by themselves.

You know most users don't know how to solve incorrect blocking, ex: Line Today.
You can't say that users add some specific domains in the whitelist by themselves.
They don't have the knowledge.
It's better that you give the default whitelist and let users decide to enable it or not.

The content in the new filter (whitelist):
Comments for every rule.
ex:
! Read news on Line Today, or watch videos on Line TV website:
@@||www.google-analytics.com
@@||www-google-analytics.l.google.com

! Open the pages on https://www.hardgraft.com/
@@||chimpstatic.com

! Play the videos on https://ck101.com/
@@||ads.ck101.com

! Show the links on http://boo.tw/
@@||pagead2.googlesyndication.com

! Play videos on some websites.
@@||imasdk.googleapis.com

! https://github.com/AdguardTeam/AdguardFilters/issues/21669
! Play the videos on https://www.4gtv.tv/
@@||googleads.g.doubleclick.net

**Comment by ameshkov** [comment]
I understand the idea, but it seems to be region-specific (this Line Today issue is the most important one I guess). Tbh, I still don't like the idea of unblocking Google Analytics in general, but I can understand why it might be necessary.

We can add something like "AdGuard SDN unbreak filter" which will include this kind of wide exclusions and let people decide on their own if they want to use it.

**Comment by lancelot-moon** [comment]
Thank you very much.
My thought is to let users do choice and take the risk by themselves after users understand the risk.

Sometimes users add more and more hosts files and meet more incorrect blocking.
I think such kind of default whitelist is helpful.
You decide the new filter' name.))

**Comment by lancelot-moon** [comment]
I add some examples...
Except for AG SDN filter, user may subscribe to other hosts files in the future.
We actively make the default whitelist for solving incorrect blocking and anti-adblock on DNS level, which is better.

Users report issues.
AG filters developers can collect and add those domains which can't be blocked into the default whitelist.

**Comment by lancelot-moon** [comment]
@AdamWr

This is my whitelist for only DNS filtering.
Unblocking them won't cause anti-adblock or incorrect blocking.
Although we unblock them on DNS level, we still can block them or make better rules in HTTPS filtering.

pagead2.googlesyndication.com
www.google-analytics.com
imasdk.googleapis.com
ads.ck101.com
chimpstatic.com
cleverbridge.com
pstmrk.it
ahd.ruten.com.tw
ad.ettoday.net
googleadapis.l.google.com
www-google-analytics.l.google.com
googleads.g.doubleclick.net
pubads.g.doubleclick.net
l.doubleclick.net
pagead46.l.doubleclick.net

But I meet trouble when I subscribes hosts files in my router and only wants to unblock certain sub-domains.
https://github.com/AdguardTeam/AdguardFilters/issues/30487#issuecomment-478457586

https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt

I found an strange thing.
ex: 0.0.0.0 google-analytics.com in AdguardDNS.txt.
If I add www.google-analytics.com in my router's whitelist, www.google-analytics.com still can't be resolved.
The DNS response is 0.0.0.0.
I must add google-analytics.com in my router's whitelist.
Simply unblocking sub-domains is invalid in my router.
I need to unblock the whole domains, which is bad.

**Comment by Yuki2718** [comment]
FWIW it's mine:
```
@@||79423.analytics.edgekey.net^|
@@||ac.ebis.ne.jp^|
@@||c.amazon-adsystem.com^|
@@||doubleclick.net^|
@@||google-analytics.com^|
@@||prf.hn^|
@@||ranking.rakuten.co.jp^|
```

I guess I need to make issues on SDNS filter for some of them.

**Comment by lancelot-moon** [comment]
I disagree the rule, `@@||doubleclick.net^`.

**Comment by Yuki2718** [comment]
> I disagree the rule, `@@||doubleclick.net^`.

That's all the matter of a setup. All of my devices have client-side blocker installed, so those occasional FPs and anti-adblock trigger by doubleclick are not worth my time to be spent.
