### ISSUE TITLE
Problem with List-KR Filter

### ISSUE THREAD

**Issue by ptrkr** [AdguardTeam/FiltersRegistry#157]
Forwarded from https://github.com/AdguardTeam/FiltersRegistry/issues/151

@ameshkov @Alex-302 Thanks for answer! But i have a problem with filter subscription that '(Obsolute) List-KR' is still displayed in the subscription list like this:
![cap-0084](https://user-images.githubusercontent.com/27128153/51579846-c7450e80-1f05-11e9-9fdf-3d698071b354.png)
And when i visit korean websites which have web-advertisements, the filter doesn't seem to be automatically activated. I think it's because YousList is set as the default korean filter.. what can i do for resolve this problem?

**Comment by ptrkr** [comment]
.

**Comment by ptrkr** [comment]
@ameshkov @Alex-302 Ping! may i can get pong response? :D

**Comment by Alex-302** [comment]
it will be fixed, please wait

**Comment by ptrkr** [comment]
Umm ok. time will solve it..
