### ISSUE TITLE
Rename "spyware filter" to "tracking protection filter"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#159]
`AdGuard Spyware filter` --> `AdGuard Tracking Protection filter`

@aalpatkina plz take a look, this needs to be done on oneskyapp as well.

**Comment by lancelot-moon** [comment]
`AdGuard Spyware filter` -> `AdGuard Tracking Protection filter`

Miscellaneous / Glossary:
#44118051

Miscellaneous / Miscellaneous:
#43732149
#43732150
#43732118

Adguard for Mac / Glossary:
#44117354

Adguard for Mac / Adguard for Mac:
#40189954

Website / Glossary:
#44117555

Website / adguard.com:
#39574664
#39574892

**Comment by ameshkov** [comment]
@lancelot-moon thank you!

@aalpatkina @Mizzick guys, could you plz do it in oneskyapp?

**Comment by aalpatkina** [comment]
Done
