### ISSUE TITLE
ADD Popup filter

### ISSUE THREAD

**Issue by kano1** [AdguardTeam/FiltersRegistry#170]
I'm not bothered by the billboard, but the most annoying is the popup
I saw several filters that included a portion of the popup block in https://filterlists.com

1 Fanboy Annoyances 
2 Adware Filter Block
3 Polish Annoyance Filters - Pop-ups

these three filters might satisfy the user
and when I use these three filters I also feel that browsing speed is increasing
but if you have a new list of filters you might have to double-check the filter because the possibility of lack of a white list can be a problem 
or you have to separate filters for popups to activate or deactivate in different forms from the billboard block filter

**Comment by Alex-302** [comment]
Hi
We have own Annoyances filter. You can report about annoying elements.

**Comment by kano1** [comment]
ok

**Comment by kano1** [comment]
go animeindo.moe
block a all of popups on this site
this is anoying popup

**Comment by Alex-302** [comment]
@kano1 please send report using AdGuard or https://github.com/AdguardTeam/AdguardFilters/issues/new

**Comment by kano1** [comment]
ok i see thakyou
