### ISSUE TITLE
AlleBlock list - wrong URL

### ISSUE THREAD

**Issue by maciejtarmas** [AdguardTeam/FiltersRegistry#18]
Hi, thanks for adding my list with [this commit](https://github.com/AdguardTeam/FiltersRegistry/commit/7a3c01059bf83f801eb3a4d4792123e3e8224ccd), though the URL should point to https://alleblock.pl/alleblock/alleblock.txt

Could you please replace the GitHub link with the official one?

**Comment by Alex-302** [comment]
Hi. Done.
