### ISSUE TITLE
Add NPR exception

### ISSUE THREAD

**Issue by Cretezy** [AdguardTeam/FiltersRegistry#186]
https://github.com/AdguardTeam/FiltersRegistry/blob/a1834fdef02e5a9bd38a6210636b6d7d5a85b80b/filters/ThirdParty/filter_204_PeterLowesList/filter.txt#L788

https://twitter.com/Cretezy/status/1111300638254776323

http://npr.streaming.adswizz.com and http://cf-npr.streaming.adswizz.com are required to play NPR podcasts.

**Comment by Alex-302** [comment]
better report to the filter's author

**Comment by ameshkov** [comment]
@Alex-302 we should fix this in the simplified domain names filter, AG DNS is misbehaving because of this.

**Comment by ameshkov** [comment]
Meanwhile, I'll close this PR. 

@Alex-302 plz sort this out: http://github.com/AdguardTeam/AdguardSDNSFilter
