### ISSUE TITLE
Add Malware Domain List in the security group?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/FiltersRegistry#190]
https://www.malwaredomainlist.com/
http://www.malwaredomainlist.com/forums/index.php?topic=3270.0
http://www.malwaredomainlist.com/hostslist/hosts.txt

It seems that you only have `DNS-BH – Malware Domain Blocklist by RiskAnalytics` in the security group of filters.
http://www.malwaredomains.com/

Is it necessary to add Malware Domain List in the security group?

**Comment by Yuki2718** [comment]
MDL should not be added and this issue can be closed. See https://github.com/uBlockOrigin/uBlock-issues/issues/984
