### ISSUE TITLE
Mobile Ads filter list by YanFung

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#216]
@loveqqzj commented on [Thu Aug 01 2019](https://github.com/AdguardTeam/AdguardForiOS/issues/1157)

Hope to add a chinese filiter, it's very useful for many chinese webpages, his github homepage is https://github.com/YanFung/Ads.
The filiter address is https://raw.githubusercontent.com/YanFung/Ads/master/Mobile.txt
Please help to add it, thanks very much!

**Comment by ameshkov** [comment]
Let's observe it for some time

**Comment by ameshkov** [comment]
Seems good, let's replace one of the obsolete filter lists

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/FiltersRegistry/pull/238
