### ISSUE TITLE
Rules not in filter lists

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/FiltersRegistry#22]
Rules in filter lists in products are not up2date.

e. g. English/specific:

||imageweb.ws/whaledate.gif
touch.facebook.com###MNewsFeed article[data-ft*="\"ei\":\""]

Not found when updating in AdGuard for Windows (2.0.1.34). Very likely other rules too.

Those rules are found in filter.txt though.

**Comment by ameshkov** [comment]
This is due to the cache on filters.adtidy.org:
> Rate limit enforced for cache purge
