### ISSUE TITLE
Filter Description Updates

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/FiltersRegistry#222]
Whilst reinstalling AdGuard on various platforms, I noticed there could be a few changes made to the Filter descriptions for end-users.

For example, I didn't realise that Fanboy's Social Blocking List was already in the Annoyances List, as I usually enable filters from top to bottom of the list order.

Sources are provided to indicate where I got some titles and descriptions from.

## Proposed changes:

- **Peter Lowe's list**
**Title:** Change title to "Peter Lowe's Blocklist" _([source](https://www.patreon.com/blocklist))_
**From:** English
**To:** Let us be blinked at no longer! Let the flashing cease! Down with banners! Up with transfer rates! STOP THE MADNESS! _([source](http://pgl.yoyo.org/as/#about))_

- **Fanboy's Enhanced Tracking List**
**From:** filters
**To:** Blocks common tracking scripts such as Omniture, Webtrends, Foresee, Coremetrics, Google Analytics, Touch Clarity and Channel Intelligence. _([source](https://secure.fanboy.co.nz/filters.html))_

- **Fanboy's Social Blocking List**
**From:** removes social media integration — supplement for EasyList
**To:** Hide and block social content, social widgets, social scripts and social icons. (Already included in Fanboy's Annoyances List) _([source](https://secure.fanboy.co.nz/filters.html))_

- **Fanboy's Annoyances**
**From:** removes online annoyances (includes Fanboy's Social Blocking List) — supplement for EasyList
**To:** Removes in-page pop-ups and other annoyances. (Includes Fanboy's Social Blocking & Cookiemonster Lists) _([source](https://secure.fanboy.co.nz/))_

- **I don't care about cookies**
**From:** I don't care about cookies
**To:** Hides annoying cookie warnings from almost all websites and saves you from unnecessary clicks. _([source](https://www.i-dont-care-about-cookies.eu/#install))_

- **Fanboy's Cookiemonster List** 
**From:** This will remove cookie and privacy warnings (List already included in Annoyances List, don't add list if you're using the Annoyances List)
**To:** This will remove cookie and privacy warnings. (Already included in Fanboy's Annoyances List)

- **Malware Domains**
**Title:** Change title to "Malware Domain Blocklist"
**From:** malware protection
**To:** Blocks domains that are known to be used to propagate malware and spyware. _([source](http://www.malwaredomains.com/?page_id=2))_

- **Spam404**
**From:** This filter protects you from online scams
**To:** Protects you from online scams.

- **NoCoin Filter List** 
**Title:** Change title to "NoCoin Adblock List" _([source](https://github.com/hoshsadiq/adblock-nocoin-list/))_
**From:** This filter disables browser based miners such as coin-hive.
**To:** Blocks and disables "browser-based crypto mining" such as coin-hive. _([source](https://github.com/hoshsadiq/adblock-nocoin-list/))_

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement/issues/62

**Comment by ameshkov** [comment]
@AdamWr could you plz assist

**Comment by AdamWr** [comment]
Sure, answered here - https://github.com/PolishFiltersTeam/PolishAntiAnnoyingSpecialSupplement/issues/62
