### ISSUE TITLE
Is Icelandic ABP abandoned?

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#232]
We might need to mark it as obsolete if it is

**Comment by DandelionSprout** [comment]
This is probably extremely belated for me to answer to, but it appears to have got one update in the past year, apparently on the 6th of July (UTC).

I would personally consider an anti-ad list to be abandoned if it received *zero* updates for 12 months straight.

**Comment by DandelionSprout** [comment]
For that matter, *Filtros Nauscopicos* still hasn't been listed as Obsolete, despite it last having been updated in 2013, apparently. I think that would be a slightly more pressuring matter to attend to as far obsoleted lists go.

**Comment by ameshkov** [comment]
Yeah, thanks for mentioning this! @Alex-302 can you plz mark Filtros Nauscopicos obsolete?

**Comment by Alex-302** [comment]
> can you plz mark Filtros Nauscopicos obsolete?

ok
