### ISSUE TITLE
Consider making AdBlockID recommended (Indonesian)

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersRegistry#235]
https://github.com/realodix/AdBlockID

**Comment by ameshkov** [comment]
Nice! What Indonesian filter list do we have as recommended by default at the moment?

Should we consider changing it to this?

**Comment by Alex-302** [comment]
At the moment ABPindo is recommended.
@realodix says that AdBlockID is a separate filter https://github.com/realodix/AdBlockID/issues/45#issuecomment-543141189

> Should we consider changing it to this?

I think we can do it after some time.

**Comment by ameshkov** [comment]
Well, let's add it, and then rename this issue in "Consider making AdBlockID recommended".

**Comment by Alex-302** [comment]
ok

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/53093

**Comment by Alex-302** [comment]
@3xploiton3 What can you say about it as Indonesian user? Should we make it recommended?

**Comment by 3xploiton3** [comment]
> @3xploiton3 What can you say about it as Indonesian user? Should we make it recommended?

absolutly yes, Highly recommended,

they are very active to maintain filters
