### ISSUE TITLE
Add Indian Filter

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersRegistry#250]
@pidus commented on [Tue Oct 29 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/3178)

### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer

### Problem Description
AdGuard has plenty of language specific filter lists to choose. But, an Indian list is not present. This list can be found in the Fanboy's website's regional section: https://www.fanboy.co.nz/regional.html
Direct link to the list: https://www.fanboy.co.nz/fanboy-indian.txt

### Proposed Solution
Add the Indian filter list to the language-specific filters section.

**Comment by ameshkov** [comment]
Fanboy's filter list is really tiny and VERY old. Also, half of websites mentioned there are dead.

**Comment by krystian3w** [comment]
Also dropped support:

`!!!!!!!!!!!!!!!! Officially unsupported !!!!!!!!!!!!!!`

**Comment by krystian3w** [comment]
Project may back to live, I no longer see "Officially unsupported".

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersRegistry/issues/550
