### ISSUE TITLE
Valid rules marked as invalid

### ISSUE THREAD

**Issue by realodix** [AdguardTeam/FiltersRegistry#259]
Why this rules is marked "invalid selector" ?

- `##[href*="text" i]`
- `##img[alt*="text" i]`
- `##img[title*="text" i]`
- `##a[alt*="text" i] `
- `##a[title*="text" i]`

**Comment by AdamWr** [comment]
I guess it's the same issue as here - https://github.com/AdguardTeam/FiltersCompiler/issues/41
