### ISSUE TITLE
m.douban.com

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/FiltersRegistry#264]
@adguard-bot commented on [Wed Nov 20 2019](https://github.com/AdguardTeam/AdguardFilters/issues/44417)

### Issue URL (Incorrect Blocking)
[https://m.douban.com/group/topic/141660676/?author=1#sep](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fm.douban.com%2Fgroup%2Ftopic%2F141660676%2F%3Fauthor%3D1%23sep)
### Comment
> Incorrect blocking
> 
> @zloyden

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/pCTiNc8.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/9C40iA0.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | iOS
AdGuard version: | 2.1.2
Browser: | Safari
System wide filtering: | disabled
Simplified filters: | disabled
AdGuard DNS: | None
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> AdGuard Safari<br/><br/><b>Language-specific:</b><br/> AdGuard Japanese, <br/>EasyList China, <br/>CJX's Annoyance List

---

@zloyden commented on [Wed Nov 20 2019](https://github.com/AdguardTeam/AdguardFilters/issues/44417#issuecomment-555948185)

It's caused by `EasyList China`. Please make a report to their forum.
Also you can add the rule to User Rules: `@@||douban.com^$subdocument`

---

@accountforadg commented on [Mon Nov 25 2019](https://github.com/AdguardTeam/AdguardFilters/issues/44417#issuecomment-557953275)

@zloyden  

Can you fix this problem from your side? 

Because
   after communication, Easylist China they don't think the reason for this problem is their code.

---

@accountforadg commented on [Mon Nov 25 2019](https://github.com/AdguardTeam/AdguardFilters/issues/44417#issuecomment-558119352)

@BlazDT   
@AdamWr 

help

**Comment by ameshkov** [comment]
@zloyden EasyList China is supposed to be used with traditional ad blockers, and this issue is caused by iOS content blocker limitations. I guess it's right that we're handling this issue on our side.
