### ISSUE TITLE
Pi-Hole-Lists

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/FiltersRegistry#266]
@ameshkov Has anyone brought up the lists @ https://github.com/Akamaru/Pi-Hole-Lists/?  I guess they're best used as DNS-block, given πhole.  I ran into it via Google search, as, uncommonly, the _Other_ list seems to block `0i0i0i0.com`. The [ReadMe](https://github.com/Akamaru/Pi-Hole-Lists/blob/master/README.md) gives the complete meta-list.  The GTranslate is:
>My lists for Pi-Hole.
>
>Installation
>
>Just add it to the Pi-Hole Settings page in the "Block Lists" tab.
>
>Lists
>
>Block ads in apps on iOS and Android
https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/mobile.txt
>
>To block advertising on SmartTVs (HbbTV and co.)
https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/smarttv.txt
>
>To block Adobe Updates (Photoshop & co.)
https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/adobeblock.txt
>
>To block Nintendo system updates (3DS / Wii U / Switch)
https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/nintendoblock.txt
>
>To block tracking and information that Windows collects
https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/nomsdata.txt
>
>Block Fake Jailbreak Websites (Domains of The iPhone Wiki)
https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/jbfake.txt
>
>To block fake gaming websites (fake emulators, etc.)
https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/gamefake.txt
>
>To block German fake news websites
https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/fakenewsde.txt
>
>To block Cryptominer
https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/cryptomine.txt
>
>To block other things that I could not assign anywhere
https://raw.githubusercontent.com/Akamaru/Pi-Hole-Lists/master/other.txt

**Comment by ameshkov** [comment]
Merged into https://github.com/AdguardTeam/FiltersRegistry/issues/68

We'll do this when DNS filtering comes to Win and Mac.

**Comment by TPS** [comment]
N.B.: Most of these make sense for mobile, as well, so do consider for that, also. 🙇🏾‍♂️
