### ISSUE TITLE
Scriptlet rules are (presumably incorrectly) removed from natively included third-party lists during CI build conversion

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/FiltersRegistry#267]
Hello again.

In the past 2 days I've done my best attempt at converting `##+js` entries from [the uBO main version of my Nordic list](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianList.txt), into `#%#//scriptlet` entries for [the AdGuard version](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersAdGuard.txt), in attempted accordance with [the closest thing to a documentation on `#%#//scriptlet` I could find](https://github.com/AdguardTeam/AdguardBrowserExtension/blob/master/Extension/lib/filter/rules/scriptlets/scriptlets.js).

But unfortunately, judging by https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_249_NorwegianList/diff.txt as of at the time of writing, and its mentions of `(...) is excluded by: #%#`, it appears that the CI builds' filter converter for natively included third-party lists is set to exclude **all** `#%#` entries by default, presumably to avoid conflict with ABP's scriptlet entry syntax; which makes quite a large number of more advanced AdGuard syntaxes completely unavailable for natively included lists, but available for lists that are loaded **non**-natively.

Would it be possible to remove the CI build's exclusion of `#%#` entries, or at least for `#%#//scriptlet`?

**Comment by Alex-302** [comment]
Hi
https://github.com/AdguardTeam/FiltersCompiler/issues/61

**Comment by ameshkov** [comment]
Yeah, we should first do AdguardTeam/FiltersCompiler#61 and then we'll be able to configure "high" trust level for your filter lists.

**Comment by DandelionSprout** [comment]
Sounds like a good solution/idea to me. 👍

**Comment by ameshkov** [comment]
Oh, and one more thing, there's actually no need to convert `##+js`, you'd better keep using the uBO syntax as it is compatible with AdGuard anyway. Managing one list is easier than converting rules manually:)

**Comment by krystian3w** [comment]
Possible repair bug with `"` character in `remove-attr` (ra) scriplet?

**Comment by slavaleleka** [comment]
@krystian3w 
that's because of the same type of quotes for defining the parameter and inside of it. it will be fixed soon. thanks!
