### ISSUE TITLE
KAD - why not all rules are used???

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/FiltersRegistry#268]
https://github.com/PolishFiltersTeam/KAD/blob/master/KAD.txt
have 2409 lines
Adguard for Windows and Extension in Browser using only 62 lines!!

![20191204-1575487435-001](https://user-images.githubusercontent.com/9846948/70173846-03273380-16d4-11ea-834a-cb23ae6f19af.png)
![20191204-1575487454-001](https://user-images.githubusercontent.com/9846948/70173865-0d493200-16d4-11ea-9cd8-af41e8c154e4.png)
![20191204-1575487476-001](https://user-images.githubusercontent.com/9846948/70173888-1afeb780-16d4-11ea-9043-b8870fd35f3d.png)

@AdamWr  @ameshkov  @hawkeye116477  @azet12

**Comment by ameshkov** [comment]
This is because AdGuard does not accept $all modifier from third-party filter lists.

We'll fix this soon

**Comment by hawkeye116477** [comment]
It's because filters compiler marks rules with `all` modifier as invalid.
https://github.com/AdguardTeam/FiltersCompiler/issues/58

**Comment by ameshkov** [comment]
There's a number of improvements coming -- scriptlets, $all and some other modifiers won't be discarded

**Comment by FadeMind** [comment]
@ameshkov  @hawkeye116477  thanks for fast response ;) 
For now paused in stable against crashing with lastest nightly 😬
