### ISSUE TITLE
Filters against ransomware

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#28]
> 1) Against Ransomware
https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt
https://ransomwaretracker.abuse.ch/downloads/RW_URLBL.txt
https://ransomwaretracker.abuse.ch/downloads/RW_IPBL.txt

I'll be keeping eye on these lists, don't do anything yet.

**Comment by lancelot-moon** [comment]
https://ransomwaretracker.abuse.ch/
Ransomware Tracker has been discontinued on Dec 8th, 2019
A pity...

**Comment by ameshkov** [comment]
:(
