### ISSUE TITLE
exclude ##^ vs new conversion to $$script[tag-content]

### ISSUE THREAD

**Issue by krystian3w** [AdguardTeam/FiltersRegistry#280]
https://github.com/AdguardTeam/FiltersRegistry/blob/ac33fd92c7b46a5086958fb5c2dead0fadfd30b0/filters/exclusions.txt#L19

* https://github.com/AdguardTeam/FiltersCompiler/issues/60

* https://github.com/AdguardTeam/FiltersCompiler/issues/61 (trust level for list unknown)

Examples in ThirdParty:

https://github.com/AdguardTeam/FiltersRegistry/blob/ac33fd92c7b46a5086958fb5c2dead0fadfd30b0/filters/ThirdParty/filter_237_PolishAnnoyance/diff.txt#L63-L64

https://github.com/AdguardTeam/FiltersRegistry/blob/ac33fd92c7b46a5086958fb5c2dead0fadfd30b0/filters/ThirdParty/filter_217_PolskiFiltrCookies/diff.txt#L126-L127

**Comment by ameshkov** [comment]
Yep, I guess the exclusion is not needed anymore.

@tvinzz ?

**Comment by krystian3w** [comment]
Maybe help in tests:

https://gorhill.github.io/uBlock/tests/procedural-html-filters.html
