### ISSUE TITLE
Update locales from Crowdin again

### ISSUE THREAD

**Issue by xyb994** [AdguardTeam/FiltersRegistry#284]
I just noticed `AdGuard Tracking Protection filter` is showing up as `间谍软件过滤器` (malware softwares filter) in iOS app, which does not make sense since the filter is listed under `Privacy` category. 

A bit of tracking down led me to this repo. Looks like the mistranslation was [introduced in this repo's initial commit](https://github.com/AdguardTeam/FiltersRegistry/blame/424756f8cc50fa760889011b2918e322d8772c93/locales/zh/filters.json#L11).

I saw Crowdin translation was brought in on Jul 23, 2019 in #214 , but a correct translation was only [added on 2019-08-08 on Crowdin](https://crowdin.com/translate/adguard-applications/17580/en-zhcn#q=filter.3.name).

**Comment by ameshkov** [comment]
@xyb994 thank you, we'll fix it!

**Comment by tvinzz** [comment]
https://github.com/AdguardTeam/FiltersRegistry/pull/300
