### ISSUE TITLE
Rename 'Fanboy's Cookiemonster List' to 'EasyList Cookie List'

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#301]
@superlex commented on [Sat Feb 01 2020](https://github.com/AdguardTeam/AdGuardForSafari/issues/314)

### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

Details here:
https://github.com/AdguardTeam/FiltersRegistry/pull/270

In AG for Safari v.1.6.4 it still has the old name, while in AG ext, AG for Android, etc, it has the new one.

Thanks :)

**Comment by krystian3w** [comment]
EasyList/Adblock Plus have law troubles with hosts:

`https://easylist.to/easylist/fanboy-annoyance.txt`
`https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt`

https://github.com/AdguardTeam/FiltersRegistry/blob/4f2f956af390b283c34a9441025be3d08c971760/filters/ThirdParty/filter_122_FanboysAnnoyances/template.txt#L2

Recommend is watch when URL-s serve outdated version or error 404 and then change to:

`https://secure.fanboy.co.nz/fanboy-annoyance.txt`

or

`https://fanboy.co.nz/fanboy-annoyance.txt`

**Comment by Alex-302** [comment]
It seems they works now.

**Comment by krystian3w** [comment]
#637 #635

**Comment by krystian3w** [comment]
https://github.com/easylist/easylist/issues/14245
