### ISSUE TITLE
Rule "||edgesuite.net" in "Thai Ads Filters" has blocked all "edgesuite.net" CDN.

### ISSUE THREAD

**Issue by hezhijie0327** [AdguardTeam/FiltersRegistry#303]
Can you fix this problem from your side? I've reported this issue to them, but it's still pending. It affects many websites,  such as Microsoft, Apple, Steam, etc.

Environment: AdGuard Home on Ubuntu

// Source:
https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_202_Adblock-Thai/filter.txt

// Logs:
Blocked by CNAME or IP in response
CNAME: play-cdn.itunes-apple.com.akadns.net. (ttl=2323)
CNAME: play.itunes.apple.com.edgesuite.net. (ttl=2323)
CNAME: a1806.dscb.akamai.net. (ttl=192)
AAAA: 2600:1406:3::b81c:bcc2 (ttl=8)
AAAA: 2600:1406:3::b81c:bcc3 (ttl=8)

// Known issues:
ax.itunes.apple.com
init.ess.apple.com
init-p01md.apple.com
isrg.trustid.ocsp.identrust.com
steamcdn-a.akamaihd.net
ocsp.int-x3.letsencrypt.org
officecdn.microsoft.com.edgesuite.net
... ...

**Comment by Alex-302** [comment]
https://github.com/adblock-thai/thai-ads-filter/issues/8

**Comment by hezhijie0327** [comment]
FIXED
