### ISSUE TITLE
Create a filter for blocking comments

### ISSUE THREAD

**Issue by AlikhanAliev** [AdguardTeam/FiltersRegistry#309]
References:

![image](https://user-images.githubusercontent.com/30260021/75669089-70267700-5c8b-11ea-981e-70762e10b301.png)
![image](https://user-images.githubusercontent.com/30260021/75669100-761c5800-5c8b-11ea-800d-3488c0ef8554.png)

**Comment by Alex-302** [comment]
There are to possible variants:
* hide comments and block request;
```
youtube.com##ytd-comments
||youtube.com/comment_service_ajax
```
* create JS/scriptlet, that will collapse comments and add button to show them(probably without blocking of request)

**Comment by slavaleleka** [comment]
such scriptlet (or redirect) is going to be implemented for Disqus
https://github.com/AdguardTeam/Scriptlets/issues/53

but for Youtube and other common comment services it can be made as well

**Comment by DandelionSprout** [comment]
I maintain https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AntiAwfulCommentsList.txt for cases where I felt that the comments would make peoples' lives worse if they read them, if that counts for anything.

**Comment by zloyden** [comment]
More like using a scriptlet or redirect. Last one we [already have - click2load.html](https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-redirects.md#click2load.html).
