### ISSUE TITLE
DuckDuckGo Tracker Radar

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/FiltersRegistry#310]
The [CCBY-NC-ND 4.0-licensed](https://github.com/duckduckgo/tracker-radar/blob/master/LICENSE) source repo's @ https://github.com/duckduckgo/tracker-radar/.

From the [ReadMe](https://github.com/duckduckgo/tracker-radar/blob/master/README.md):
> This data set consists of the most common cross-site trackers with data about their tracking behavior. It allows for easy custom solutions with the significant metadata it has for trackers: parent entity, prevalence, use of fingerprinting, cookies, privacy policy, and performance. The data on individual tracker domains can be found in the domains directory.

From the [introductory blog post](https://spreadprivacy.com/duckduckgo-tracker-radar/):
> This data set is now publicly available to use for research and for generating tracker block lists. And, the code behind it is now open source.

> Developers can use it to make their own custom tracker block lists.

As of right now, there _isn't_ a single file version ~~(https://github.com/duckduckgo/tracker-radar/issues/2 tracks a request for a `hosts`-file version)~~, so this'll take some effort to transform into a filterlist.

**Comment by ameshkov** [comment]
Well, we'd better wait for a single file version. I don't see anything really new in this list.

**Comment by TPS** [comment]
Based on the exchange from that thread, they're not going to provide such a single-file version:
>@ jdorweiler So, just to clarify, y'all don't want to publish any kind of app-ready final product (even just plain text or hosts list), but are providing this repo solely so that developers can format the data themselves & include into their own apps?

>@TPS that's right

**Comment by curbengh** [comment]
I extracted all the links that Tracker Radar detected to contain browser fingerprinting and store them in https://gitlab.com/curben/tracking-data. The links include javascript links and webpages that have javascript with fingerprinting stuff. Currently it's just a list, not a blocklist; the list has many entries that are not suitable for blocklist purpose, e.g. `youtube.com/embed/*`.

The Tracker Radar data is actually licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/), it's the DuckDuckGo logos that are licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/). ND would have prevented the data from being adapted as a blocklist.
