### ISSUE TITLE
Update source link

### ISSUE THREAD

**Issue by PentagramTr** [AdguardTeam/FiltersRegistry#334]
ChinaList+EasyList source link redirects to a broken page.

<details><summary>Screenshot:</summary>

![chi](https://user-images.githubusercontent.com/34379403/82104542-052ffc80-9720-11ea-9e97-a79f6f3c0464.png)

</details>

**Comment by Alex-302** [comment]
Address is correct, but they do not add content:)
http://web.archive.org/web/20140315000000*/http://www.adtchrome.com/extension/adt-chinalist-easylist.html
![image](https://user-images.githubusercontent.com/8361299/82216555-c5d0fe00-9921-11ea-97cb-afee44f674e7.png)

**Comment by DandelionSprout** [comment]
Going pretty in-depth on https://www.adtchrome.com/, shows me that the list is specifically designed for a strange adblocker named Ad Terminator, for which the last update was in February 2019 (which was honestly more recent than I thought it would be).

There's a number of other oddities as well, such as how that list does not actually include EasyList; and how Ad Terminator also has [a pretty heavily encrypted "VideoList" list file thingie](https://sub.adtchrome.com/videoadjs.txt).

**Comment by Alex-302** [comment]
> also has [a pretty heavily encrypted "VideoList" list file thingie](https://sub.adtchrome.com/videoadjs.txt)
this is BASE64

**Comment by DandelionSprout** [comment]
Ah, okay. That explains it.

I have generally very little experience with Base64 and Base32 and such, sadly.
