### ISSUE TITLE
Add "ADgk Mobile China list"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#342]
* Name: "ADgk Mobile China list"
* Homepage: http://adgk.net
* File: https://gitee.com/banbendalao/adguard/raw/master/ADgk.txt
* Language: `zh`

Please add Chinese translation for it's name as well:
* zh: `adgk手机去广告规则`
* zh-TW: `adgk手機去廣告規則`

**Comment by lancelot-moon** [comment]
For better looking, I suggest to add a gap between English and Chinese.
zh: adgk 手机去广告规则
zh-TW: adgk 手機去廣告規則

**Comment by ameshkov** [comment]
@Alex-302 could you please also use it for some time and see if it breaks anything?

**Comment by Alex-302** [comment]
ok

**Comment by Yuki2718** [comment]
I'll check lator.

**Comment by Yuki2718** [comment]
The list includes many `$replace` filters but IIRC won't work for 3p lists. These filters look quite generic (the 1st one may affect proxy user):
```
/:\d{5}\//$third-party,domain=~copymanga.com
/1.gif^
```
This may be garbled?
`591hx.com##div.banner,img[alt*="���"]`

Also `$mp4` modifier is deprecated, better to be replaced with `$redirect`.

@banbendalao

**Comment by zloyden** [comment]
I agree with that. `$replace` rules will be excluded anyway.

**Comment by ameshkov** [comment]
There're a couple of things to note about the list:

1. As Yuki said, it does include a lot of `$replace` rules. If we include it to FiltersRegistry, it would basically cripple the list since $replace won't work. I am not sure we'll do any good this way.
2. The list targets AdGuard for Android specifically, not other versions.

**Comment by zloyden** [comment]
Yeah, that makes sense. I suppose we can't add the filter to FiltersRegistry?

**Comment by Yuki2718** [comment]
The maintainer responded quickly and fixed most of what I pointed out. Maybe he can do something about `$replace` too.

**Comment by ameshkov** [comment]
As I understand, there're a lot of things in China net for which `$replace` rules are necessary to handle. Maybe we could provide some shortcuts or modifiers that would be safe for 3p lists to use and would cover most of the cases?
