### ISSUE TITLE
pl.weekendmaxmara.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersRegistry#352]
@adguard-bot commented on [Fri Jun 12 2020](https://github.com/AdguardTeam/AdguardFilters/issues/57265)

### Issue URL (Incorrect Blocking)
 [https://pl.weekendmaxmara.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fpl.weekendmaxmara.com%2F)
### Comment
> bez agduarda działa, z nie

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/gONrhlc.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/TVZAXjU.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Ext
AdGuard version: | 3.4.31
Browser: | Chrome
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing third-party cookies (2880), Block WebRTC, Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection, <br/>Fanboy Anti-Facebook List<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Fanboy's Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>(Obsolete) Prebake, <br/>(Obsolete) Anti-Adblock Killer \| Reek<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Turkish, <br/>AdGuard French, <br/>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Spanish/Portuguese, <br/>EasyList Czech and Slovak, <br/>EasyList Lithuania, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>List-KR, <br/>Polskie Filtry Elementów Irytujących, <br/>Frellwit's Swedish Filter, <br/>Polski Antyirytujący Dodatek Specjalny

---

@krystian3w commented on [Sat Jun 13 2020](https://github.com/AdguardTeam/AdguardFilters/issues/57265#issuecomment-643647521)

Problemu nie robią:
```
Polski Antyirytujący Dodatek Specjalny
Official Polish filters for AdBlock, uBlock Origin & AdGuard, 
Polskie Filtry Elementów Irytujących, 
```

resztę trzeba by sprawdzać z rejestratorem lub wyłączając lista po liście.

---

@Alex-302 commented on [Mon Jun 15 2020](https://github.com/AdguardTeam/AdguardFilters/issues/57265#issuecomment-644037521)

Please disable `Prebake` filter.

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersRegistry/blob/2702178b038e99e6bca8eae6ce1362674b780b05/filters/ThirdParty/filter_209_Prebake/filter.txt#L249

`gg.pl##body > div:nth-of-type(2) > div` also is bad, hide header after scroll:

#@#body > div:nth-of-type(2) > div
![obraz](https://user-images.githubusercontent.com/35370833/85211439-84c97080-b349-11ea-98cb-60eebf34aeee.png)
