### ISSUE TITLE
Add "adg-kall China list" 

### ISSUE THREAD

**Issue by thb007** [AdguardTeam/FiltersRegistry#356]
Name: "adg-kall"
Homepage: https://github.com/thb007/Adg-kall
File: https://raw.githubusercontent.com/thb007/Adg-kall/master/adg-kall.txt
Language: zh
Rule adaptation range: pc, android, apple (some rules are not supported by the apple system), adguardhome

**Comment by byyxx128** [comment]
### You need to improve your Chinese first...
***
语文老师要被你气死……
![image](https://user-images.githubusercontent.com/20079289/85860528-85eb1980-b7f1-11ea-8046-39a350d1ad93.png)
这句话我愣没看懂啥意思……到底是只能用于 Android，还是 Android 和 PC 都可以，还是三者都能用……

**Comment by thb007** [comment]
> ### You need to improve your Chinese first...
> 语文老师要被你气死……
> ![image](https://user-images.githubusercontent.com/20079289/85860528-85eb1980-b7f1-11ea-8046-39a350d1ad93.png)
> 这句话我愣没看懂啥意思……到底是只能用于 Android，还是 Android 和 PC 都可以，还是三者都能用……

三个都可以“some rules are not supported by the apple system”我注释在apple后面所以你懂的。

**Comment by byyxx128** [comment]
### We are talking about the Chinese description. No need to translate what we are saying...
***
我说的是你中文……英文我能看懂……所以我说被气死的是语文老师而不是英语老师……
所以你应该表述为“最好是 Android、PC，苹果部分规则不支持”。注意看我的标点。

**Comment by thb007** [comment]
> ### We are talking about the Chinese description. No need to translate what we are saying...
> 我说的是你中文……英文我能看懂……所以我说被气死的是语文老师而不是英语老师……
> 所以你应该表述为“最好是安卓、PC，苹果部分规则不支持”。注意看我的标点。

我改了描述

**Comment by byyxx128** [comment]
### But you still did not fix your punctuation...
***
标点还是没改啊！顿号是关键，顿号表示并列，逗号是停顿，这是我第一次看没看懂的重要原因。另外你既然改描述了，你也得简单说下你这是干啥的……

**Comment by thb007** [comment]
> ### But you still did not fix your punctuation...
> 标点还是没改啊！顿号是关键，顿号表示并列，逗号是停顿，这是我第一次看没看懂的重要原因。另外你既然改描述了，你也得简单说下你这是干啥的……

好了。

**Comment by thb007** [comment]
> ### But you still did not fix your punctuation...
> 标点还是没改啊！顿号是关键，顿号表示并列，逗号是停顿，这是我第一次看没看懂的重要原因。另外你既然改描述了，你也得简单说下你这是干啥的……

你是不是想说我的天啊？没关系你们的官网都解释了一切。

**Comment by byyxx128** [comment]
我看到了……不过我依然不知道你这个规则是干啥的……你得简单说下你这个规则的作用啊！

**Comment by thb007** [comment]
> 我看到了……不过我依然不知道你这个规则是干啥的……你得简单说下你这个规则的作用啊！

不好意思，我不申请加入你们的中文过滤规则了，我太难了，但是我认为是金子总会发光，描述太多没意思，知道的自然懂，不知道的就当过客，谢谢。

**Comment by byyxx128** [comment]
### We are talking about the Chinese description. No need to translate what we are saying...
***
我不是官方……我是普通用户……官方没有国人……我也是本着想帮你宣传的想法才问你这些。“描述太多没意思，知道的自然懂”。我就是不知道的啊！你简单说下你这是拦截XXX，或是屏蔽XXX，或是啥的不就好了……不然你让那群老外不得看懵逼了

**Comment by thb007** [comment]
> ### We are talking about the Chinese description. No need to translate what we are saying...
> 我不是官方……我是普通用户……官方没有国人……我也是本着想帮你宣传的想法才问你这些。“描述太多没意思，知道的自然懂”。我就是不知道的啊！你简单说下你这是拦截XXX，或是屏蔽XXX，或是啥的不就好了……不然你让那群老外不得看懵逼了
> 而且我问你的另一个意思是……我想在官方收录之前自己订阅，然后我都不知道你这是干啥的

描述后面加的这个https://adguard.com/zh_cn/welcome.html网站解释了一切，如果他们再不懂就当没说，那我可以我直接关闭这个ISSUE

**Comment by byyxx128** [comment]
行吧……那你把你上面的回复删一下吧。我把我的删了，只留你主楼就行。我帮你宣传下……

**Comment by byyxx128** [comment]
This is a very famous rule users among Chinese, which can block what other rules cannot block currently.

**Comment by Alex-302** [comment]
@thb007 what is wrong?
