### ISSUE TITLE
add polish internal filters

### ISSUE THREAD

**Issue by KonoromiHimaries** [AdguardTeam/FiltersRegistry#36]
https://github.com/KonoromiHimaries/PolishSubFilters

main 
```
https://raw.githubusercontent.com/KonoromiHimaries/PolishSubFilters/master/internal-filters/wewnetrzne.txt
```

that's is a polish alternative for "Web Annoyances Ultralist"
https://github.com/AdguardTeam/FiltersRegistry/issues/63

**Comment by ameshkov** [comment]
Page not found?

**Comment by KonoromiHimaries** [comment]
@ameshkov majki move to https://github.com/MajkiIT/polish-ads-filter/tree/master/inside-filters and https://github.com/MajkiIT/polish-ads-filter/tree/master/anti-donate-filters

**Comment by ameshkov** [comment]
@KonoromiHimaries let's wait some time till the filters are stabilized then. I'll revisit this issue later.

**Comment by ameshkov** [comment]
@KonoromiHimaries uh, my bad, sorry for missing that many filter addition requests in this repo. You just reminded me about it.

Do you mind if I reopen this issue and we finally add it?

**Comment by ameshkov** [comment]
`Title: Polskie Filtry Wewnętrzne`

What filter description should we use?

**Comment by KonoromiHimaries** [comment]
![2018-11-28-window](https://user-images.githubusercontent.com/5884000/49178586-6ad3d180-f350-11e8-88a0-a7977199ff4f.png)
`Polish Internal Filters`

or

![2018-11-28-window](https://user-images.githubusercontent.com/5884000/49178636-922a9e80-f350-11e8-8c35-501e57f8d5d3.png)
`Polskie Filtry Wewnętrzne`

**Comment by ameshkov** [comment]
@KonoromiHimaries hi! it seems there's a mistake with pre-processor directives here:
https://github.com/KonoromiHimaries/PolishSubFilters/blob/master/internal-filters/zewnetrzne_listy.txt

The `!#if` and `!#endif` directives are unbalanced

**Comment by KonoromiHimaries** [comment]
@ameshkov how to i can fix this?

**Comment by ameshkov** [comment]
@KonoromiHimaries the number of `#if` must be equal to the number of `#endif` (currently, there're two `#if`s and one `#endif`)

**Comment by KonoromiHimaries** [comment]
ohh.. i see <https://github.com/KonoromiHimaries/PolishSubFilters/blob/master/internal-filters/zewnetrzne_listy.txt#L3412>

**Comment by ameshkov** [comment]
Yep, that's it
