### ISSUE TITLE
Consider outright removing "ABP Japanese filters" for being really bad

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/FiltersRegistry#360]
Directly based on Fanboy's thoughts about that list at https://github.com/collinbarrett/FilterLists/issues/1737#issue-650883236, which I'll quote verbatim:

*"We should consider removing ABP-Japanese filters, as unsupported.*

* ***Aliexpress:** Anyone wanting to shop on Alixpress.com; blocked outright with `||aliexpress.com^` Requested removal in June 2019, No fix or acknowledgement.*

* ***Youtube:** When Brave had to replace ABP-Japanese after it broke youtube: brave/adblock-lists#355*
*Related report, ~3 months, No acknowledgement, no fix: k2jp/abp-japanese-filters#60*

* ***Apple:** Broken filter affecting apple.com reported in Oct/2019, No fix or acknowledgement.*

*The sites aren't minor, and we occasionally have issues with large sites also in Easylist. But we don't ignore users or requests.*

*Last commit update was in February, but regardless of this. Given the author unwilling to fix any issues, this list should never be used or promoted. It's damaging the user experience with adblockers."*

—————————————————————

I remember the very odd support structure and high-on-the-horse maintainer from 2018-19, and I see no obvious signs that things have changed since then.

And while I am aware that AdGuard likes to stamp lists as deprecated instead of removing them; and that it already does stamp that particular list as problematic, I figured that a removal would be worth asking about, on behalf of several other people who wish for its removal from the face of the adblocking community more than I do.

I also believe the list hasn't been updated since the 5th of February either, in case that was worth mentioning.

**Comment by ameshkov** [comment]
@tvinzz maybe let's mark it as "obsolete" so that it was removed?

**Comment by Yuki2718** [comment]
It turned out "obsolete" doesn't prevent people from subscribing them very well: https://github.com/AdguardTeam/AdguardFilters/issues/58713

Well, apparently Prebake was removed: https://github.com/AdguardTeam/FiltersRegistry/pull/343

**Comment by ameshkov** [comment]
Well, there will be people who subscribed earlier, and it will take some time until we finally stop seeing this list in the reports. Hopefully not too long.
