### ISSUE TITLE
Is it possible to increase the function of filtering the country area?

### ISSUE THREAD

**Issue by julian-zhuang** [AdguardTeam/FiltersRegistry#363]
This is the case. I deployed a DNS on the public network. I only want to provide services to devices in a certain area. This can reduce the load on my server. Recently I also found some unfriendly high frequency requests, hackers? test? Maybe... 
this caused me to incur additional server fees.

thanks......

**Comment by DandelionSprout** [comment]
I get the feeling you meant to post this in https://github.com/AdguardTeam/AdGuardHome/issues, if I'm not completely wrong.

**Comment by ameshkov** [comment]
Please check the AdGuard Home repo, there is already a feature request like that.
