### ISSUE TITLE
Consider replacing filter_208_MalwareDomains with Online Malicious URL Blocklist

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/FiltersRegistry#364]
Or adding Online Malicious URL Blocklist
See 
https://github.com/gorhill/uBlock/commit/a13ac920892d25ba0bf431ea1410fd3c8612b2d6
https://github.com/uBlockOrigin/uBlock-issues/issues/1116

**Comment by Alex-302** [comment]
https://easylist-downloads.adblockplus.org/malwaredomains_full.txt is not abandoned
`! Last modified: 22 Jul 2020 14:43 UTC` 
Why it must be replaced?

**Comment by superlex** [comment]
@Alex-302 
Is it not the same list (only adapted for adblock plus)?
```
https://mirror.cedia.org.ec/malwaredomains/justdomains
https://mirror1.malwaredomains.com/files/justdomains
```
`last-modified: Tue, 19 May 2020 02:16:32 GMT`
See `www.malwaredomains.com/` too.

**Comment by krystian3w** [comment]
Yes, something script regularly bump only date, main difference is deleted empty line from origin and use ABP syntax.

![Screenshot_2020-07-23 Text Compare - An online diff tool that can find the difference between two text files](https://user-images.githubusercontent.com/35370833/88281971-e97d3f80-cce8-11ea-8a05-64297fa848ca.png) |
--- |
deleted empty line "`26407`" |

> `\|\|abp.syntax^` 

These two changes don't make the list any good support. I don't think it will add the option that Easylist there will start adding new malware domains from 2018 - 2020 on a regular basis. They seem to prefer to add them to the blocking list of ads or EasyPrivacy project.

**Comment by superlex** [comment]
Thanks for the explanation @krystian3w :)

**Comment by Alex-302** [comment]
18 Mar 2020 - 26865 lines
01 Aug 2020 - 26861 lines
It seems it is not abandoned, just no changes last 3 month.

**Comment by krystian3w** [comment]
Removed by origin domain or by EasyList python script: `PyFunceble` https://github.com/easylist/easylist/issues/2374?

**Comment by Alex-302** [comment]
No. If you compare few versions, you will find **new** rules.

**Comment by krystian3w** [comment]
I see only new 1:

`usibw.top`

And 5 deletions:

`shagarat.com`
`shannondensmore.com`
`fullsizechevy.com`
`firstline.cc`
`memoriesofalifetime.com.au`

**Comment by Yuki2718** [comment]
> I see only new 1:
> 
> `usibw.top`
> 

And that new domain is already dead.
