### ISSUE TITLE
Remove all obsoletes from Adguard products automatically.

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/FiltersRegistry#365]
Remove all obsoletes from Adguard products, how is Adguard android, all obsolete + ABP Japanese alone removed automatically (with Safari filter too). That function look good and should be in all Adguard products.

**Comment by vozersky** [comment]
@seba2282 This task is currently in progress for every product

**Comment by seba2282** [comment]
In Adguard Android I saw that, But in Extension still don't see. It come with next versions others AG products?

**Comment by vozersky** [comment]
It is just a non-public task. Yes, it comes!
