### ISSUE TITLE
tomtop.com

### ISSUE THREAD

**Issue by lcqlcq5** [AdguardTeam/FiltersRegistry#37]
1.The website was attacked and has been inserted script,But we have cleared the script.
2.As long as the buyer's browser has installed Adblock,then he cannot go shopping normally
3.We find that FiltersRegistry – filter.txt has put our website tomtop.com into the blacklist
4. Really hope you can help us to solve this problem,we want to appeal for this,if you need any information just feel free to ask us,we will reply you asap.
Best Regards

**Comment by Alex-302** [comment]
Hi
It is not blocked on my end. I don't see blocking rule for this domain in all filters. In which filter did you see this domain?
Maybe it is fixed now. Please check again.

**Comment by ameshkov** [comment]
Please note that this repo is a mere collection of different third-party filters and we do not maintain them here.

Please specify what exact `filter.txt` contains a record with your website and we will help you find who is responsible for this filter support.

**Comment by lcqlcq5** [comment]
@ameshkov Thank you very mach. [filter.txt](https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_203_hufilter/filter.txt)

**Comment by ameshkov** [comment]
@lcqlcq5 got it, this is a Hungarian filter and you can report issues with it here:
https://github.com/szpeter80/hufilter

However, I see nothing about tomtop there. The only rule that contains your domain name is `mobilarena.hu##div:not([id="page"]):not([id="shadow"]):not([id="main"]):not([id="head"]):not([id="navi"]):not([id="center"]):has(a[href*="https://www.tomtop.com"])`

But this rule is for `mobilarena.hu` website.
