### ISSUE TITLE
news.google.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersRegistry#379]
### Issue URL (Incorrect Blocking)
 [https://news.google.com/topstories?hl=de&gl=CH&ceid=CH:de](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fnews.google.com%2Ftopstories%3Fhl%3Dde%26gl%3DCH%26ceid%3DCH%3Ade)
### Comment
> Das Google News Menü öffnet sich nicht, wenn AdGuard aktiviert ist.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/j3sLSLT.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/BQ0niNV.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.0.2
Browser: | Safari
System wide filtering: | disabled
Simplified filters: | disabled
AdGuard DNS: | None
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection, <br/>EasyPrivacy, <br/>Fanboy's Enhanced Tracking List, <br/>Fanboy Anti-Facebook List<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Fanboy's Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>I don't care about cookies<br/><br/><b>Other:</b><br/> AdGuard DNS<br/><br/><b>Language-specific:</b><br/> AdGuard German

---

@Alex-302 commented on [Fri Sep 04 2020](https://github.com/AdguardTeam/AdguardFilters/issues/62440#issuecomment-687086692)

Please disable `I don't care about cookies`

**Comment by krystian3w** [comment]
Filter removed from origin source?
