### ISSUE TITLE
IP Loggers/Grabbers

### ISSUE THREAD

**Issue by Bluscream** [AdguardTeam/FiltersRegistry#38]
Referencing https://github.com/AdguardTeam/AdguardFilters/issues/6623 and https://github.com/AdguardTeam/CoreLibs/issues/70.

Simply searching some random ipgrabber domain: https://github.com/search?utf8=%E2%9C%93&q=%22bmwforum.co%22&type=Code

- https://github.com/RikoDEV/NoMoreIPLogger-adblock-list/blob/master/list.txt
- https://github.com/AegisTeam/Discord-Resources/blob/master/Domain%20Filters/Malicious/IP%20Grabbers

**Comment by KonoromiHimaries** [comment]
https://github.com/AdguardTeam/FiltersRegistry/issues/46
