### ISSUE TITLE
Upward marked as invalid selector without #?# (ExtendedCSS syntax)

### ISSUE THREAD

**Issue by krystian3w** [AdguardTeam/FiltersRegistry#381]
Examples:

* https://github.com/AdguardTeam/FiltersRegistry/blob/ab8dacfdd7cce2498dc22f3c7cf74549a892aacc/filters/ThirdParty/filter_249_NorwegianList/diff.txt#L61-L62

* https://github.com/AdguardTeam/FiltersRegistry/blob/538b9d3bc98d8e3c94c45c94106d9db605c88fbf/filters/ThirdParty/filter_243_FrellwitSwedish/diff.txt#L195-L196

So should be translated similar into:

`*##*:has(foo)` / `*##*:has-text(foo)` and many similar technolgy worth in AdGuard by ExtendedCSS.

---

related: https://github.com/AdguardTeam/ExtendedCss/issues/114

**Comment by Alex-302** [comment]
It is fixed in new compiler version.
