### ISSUE TITLE
Upload third-party filter lists metadata to Crowdin

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#390]
We should be very careful with that, not all of them are supposed to be translated.

For instance, `EasyList` needs to be kept as it is, without any translations. `EasyList Germany` == `EasyList Германия`

I think we shouldn't upload ALL of them, let's just choose the ones that can be translated.

Here's my suggestion:

* All "EasyList LANGNAME" filter lists
* hufilter
* Thai Ads Filters
* Estonian List

@slavaleleka if you see that there are any other lists that can be translated, let me know

**Comment by slavaleleka** [comment]
upload to Crowdin — ✅
