### ISSUE TITLE
mpdns is probably going to die, so merge it into adguard's dns to save our work

### ISSUE THREAD

**Issue by DaniV5** [AdguardTeam/FiltersRegistry#395]
so i have been working with spirillen on www.mypdns.org
he hasn't shown up in some days and doesn't answer my messages
i fear that he might be dead 
if so the project might die with him

i ask if you guys could merge his list into your

i have worked more in the porn list
but he got lists for everything
tracking, malware, and other things

https://www.mypdns.org/diffusion/

i want to know if this is possible and how i can help
i don't want all this work to be gone for ever

**Comment by Alex-302** [comment]
Uh, I don't know what we can do with it...

**Comment by ameshkov** [comment]
What parts of it would you suggest?

**Comment by DaniV5** [comment]
maybe some of the repos are closed to non users
but u can make a copy

he got a list of many malware sites, tracking and porn
we have been working on this for a long time

![AAAAAAAAAAAAAAAAAAAA](https://user-images.githubusercontent.com/20802412/98592899-24fc4380-22b1-11eb-980e-5bde01f0b13f.png)

can't let all this work go to waste

**Comment by DaniV5** [comment]
ok he is not dead
sorry for this
