### ISSUE TITLE
What metadata comments does Adguard support?

### ISSUE THREAD

**Issue by balupton** [AdguardTeam/FiltersRegistry#398]
I am maintaing filters at https://github.com/balupton/filters

Which uses the following metadata:

```
! Title: Vanity Filter
! Description: Disables vanity and addictive elements on Instagram, Twitter, YouTube, Medium
! Version: 1.5.2
! TimeUpdated: 2020-11-18T16:25:35Z
! Expires: 1 hour (update frequency)
! Homepage: https://github.com/balupton/filters
! License: https://unlicense.org
```

However, no matter which way I specify the `TimeUpdated` field:

- `2020-11-18T16:25:35Z` iso format
- `1605716754` unix format
- `1605716754000` [adguard format it seems](https://github.com/AdguardTeam/FiltersRegistry/blob/8572bcd8930d270d6b563d89b6f6285d46be1751/filters/ThirdParty/filter_103_BulgarianList/revision.json#L3)

AdGuard always reports the date as January 1st.

<img width="243" alt="Screen Shot 2020-11-19 at 3 25 11 am" src="https://user-images.githubusercontent.com/61148/99557462-d704df80-2a16-11eb-956c-427c6fe72809.png">

As such, the recent versions just removed the `TimeUpdated` field. And there isn't really any information on the [official docs](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters) about these metadata comments. So I'm left guessing.

**Comment by ameshkov** [comment]
Hm, it's not documented anywhere, but in fact we parse "Last Modified" if it's present. Example:
```
[ Adblock Plus 2.1]
! Checksum: /1ZnwcCAIAkP5Zymepry5A
! Version: 201508250903
! Title: EasyList China
! Chinese supplement for the EasyList filters
! Last Modified: 25 Aug 2015 09:03 UTC
! Expires: 4 days (update frequency)
! Homepage: http://abpchina.org/forum/
! License: https://easylist-downloads.adblockplus.org/COPYING
```

**Comment by balupton** [comment]
@ameshkov cool, does it support `ISO 8601` format? or the unix epoch format?

**Comment by Stillness-2** [comment]
@balupton 
Parsed fields

! Version: 123
! Title: Filter Title
! Parse next comment line after `Title` tag as description, if it is not a parsed tag. 
! Last Modified: 25 Aug 2015 09:03 UTC
! Expires: 4 days
! Homepage: http://abpchina.org/forum/

Format for `Last Modified` field is: `dd MMM y HH:mm 'UTC'`. 
Used NSDateFormatter, examples here: https://nsdateformatter.com

**Comment by balupton** [comment]
Thanks! Here is a way of getting that format from `date` CLI available on unix machines:

``` bash
date -u +"%d %b %Y %H:%M UTC"
```

**Comment by balupton** [comment]
Perhaps we should close this once the documentation page has been updated to mention this?

**Comment by balupton** [comment]
For the `Expires` field, what format does it support? As for some reason I have a `(update frequency)` suffix on mine:

```
! Expires: 1 hour (update frequency)
```

**Comment by Stillness-2** [comment]
@balupton 
`\d+\s+(day|hour).*`

**Comment by ameshkov** [comment]
Hm, I am not sure these rules are consistent among all AG products, we need to review them once again.
