### ISSUE TITLE
update name of the polish filters

### ISSUE THREAD

**Issue by KonoromiHimaries** [AdguardTeam/FiltersRegistry#40]
https://github.com/MajkiIT/polish-ads-filter#about
![2018-04-15-nano panel sterowania](https://user-images.githubusercontent.com/5884000/38775780-d833e608-408a-11e8-806c-78d1153d96a2.png)

### 1.
```
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt
```
from
```
Adblock & uBlock polish filter
```
to
```
Official Polish filters for AdBlock, uBlock Origin & AdGuard

Oficjalne polskie filtry do AdBlocka, uBlocka Origin i AdGuarda
```

##

### 2.
```
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/cookies_filters/adblock_cookies.txt
```
from 
```
Adblock & uBlock polish cookies filter
```
to
```
Polskie Filtry Ciasteczkowe

Polish Cookies Filters
```

##

### 3.
```
https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt
```
from
```
Polish Annoyance Filters
```
to
```
Polskie Filtry Elementów Irytujących

Polish Annoyance Filters
```

##

### 4.
```
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/adblock_social_list.txt
```
from
```
Polski social filtr
```
to
```
Polskie Filtry Społecznościowe

Polish Social Filters
```

##

### 5.
```
https://raw.githubusercontent.com/PolishFiltersTeam/PolishRSSFilters/master/polish_rss_filters.txt
```
from
```
Polish RSS Filters
```
to
```
Polskie Filtry RSS

Polish RSS Filters
```

##

### 6.
```
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_adguard.txt
```
from
```
Adblock & uBlock polish filter - AdGuard supplement
```
to
```
Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for AdGuard

Oficjalne polskie filtry do AdBlocka, uBlocka Origin i AdGuarda - uzupełnienie do AdGuarda
```

---

update homepage address for `Official Polish filters for AdBlock, uBlock Origin & AdGuard`, `Polskie Filtry Ciasteczkowe` and `Polskie Filtry Społecznościowe` to

```
https://github.com/MajkiIT/polish-ads-filter#polish-filters-for-adblock-ublock-origin--adguard
```

**Comment by KonoromiHimaries** [comment]
@AdamWr and you can actualize homepage address for `Official Polish filters for AdBlock, uBlock Origin & AdGuard
`

```
https://github.com/MajkiIT/polish-ads-filter#polish-filters-for-adblock-ublock-origin--adguard
```

**Comment by KonoromiHimaries** [comment]
### 6.
```
https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock_adguard.txt
```
from
```
Adblock & uBlock polish filter - AdGuard supplement
```
to
```
Official Polish filters for AdBlock, uBlock Origin & AdGuard - supplement for AdGuard
```

**Comment by Alex-302** [comment]
Hmm. Maybe it is not a good idea - replacing Eng names(translated original Polish names) by Polish. I think it will be better if you update the names in Polish lang on oneskyapp.

**Comment by ameshkov** [comment]
Yep, `FiltersRegistry` supports localization, we can have a polish translation along with the english name no problem.

**Comment by ameshkov** [comment]
On the other hand, we'll move language-specific filters to a "Language-specific" group so it shouldn't be a problem.

**Comment by hawkeye116477** [comment]
Also homepage for Polish Annoyance Filters should be changed to `https://polishannoyancefilters.netlify.com`

**Comment by hawkeye116477** [comment]
Description of Polish Annoyance Filters now should be:
`Filters that hide and block pop-ups, widgets, newsletters, push notifications, arrows and other irritating elements (includes Polish Cookies Filters).`

**Comment by ameshkov** [comment]
@AdamWr could you plz update the PR once again?

**Comment by AdamWr** [comment]
Done.
