### ISSUE TITLE
Add Actually Legitimate URL Shortener Tool

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#401]
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt

Category: privacy
Tags: privacy
Description: see https://github.com/AdguardTeam/FiltersRegistry/issues/400#issuecomment-792999470

**Comment by DandelionSprout** [comment]
Near-identical to the in-list `! Description:` value:

*"In a world dominated by bit.ly, ad.fly, and several thousand other malware injectors, this list reduces the length of URLs in a much more legitimate and transparent manner. Essentially, it automatically removes unnecessary $/& values from the URLs, making them easier to copy from the URL bar and pasting elsewhere as links."*

**Comment by ameshkov** [comment]
There's one thing that bothers me: $removeparam is not supported by the browser extension (it'll be soon, but not yet) and by Safari/iOS (never will be).

We should be able to control this on the server-side and choose for which platforms the lists are compiled.

A task for https://github.com/AdguardTeam/FiltersCompiler

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/78286

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/78286 https://github.com/AdguardTeam/FiltersRegistry/issues/448

**Comment by krystian3w** [comment]
#445
