### ISSUE TITLE
AlleBlock as to remove (obsolete)? 

### ISSUE THREAD

**Issue by seba2282** [AdguardTeam/FiltersRegistry#411]
AlleBlock as to remove (obsolete)? 
Filter is not updated longer time (last update june 2019). Are alternative filter to block ads on Allegro, otomoto, etc or any alternatives and project rip definitelly?

**Comment by AroKol78** [comment]
AlleBlock is back

**Comment by seba2282** [comment]
> AlleBlock is back

I asked that when all was going to Alleblock EOL. 

@AdamWr, author Alleblock told about continue only for Allegro. What about otomoto, etc then? Ads will stay or Adguard team put rules to some filters for that sites? 

@ameshkov the same ask to you.

**Comment by AdamWr** [comment]
@seba2282 Please report ads using reporting tool - https://reports.adguard.com/pl/new_issue.html and then we will see if it should be blocked or not.

**Comment by seba2282** [comment]
@AdamWr I will report then if I will be on PC and will see some ads on that types sites. Thank you for helping. :)

**Comment by krystian3w** [comment]
I think again down: https://github.com/maciejtarmas/AlleBlock/commits/master 1,5 year gap:

![obraz](https://user-images.githubusercontent.com/35370833/221369615-7504606e-2361-4b0c-8c83-84a1b949ec92.png) |
--- |

**Comment by piquark6046** [comment]
@zloyden Please take a look.

**Comment by seba2282** [comment]
> I think again down: https://github.com/maciejtarmas/AlleBlock/commits/master 1,52 year gap:
> 
> <a href="https://www.wolframalpha.com/input?i=+Aug+18%2C+2021+to+today" title="https://www.wolframalpha.com/input?i=+Aug+18%2C+2021+to+today">
> 
> ![obraz](https://user-images.githubusercontent.com/35370833/221369615-7504606e-2361-4b0c-8c83-84a1b949ec92.png) |
> --- |
> 
> 
> </a>

@AdamWr still not obsolete alleblock? 
I think you see with @ameshkov, @Alex-302 too

**Comment by krystian3w** [comment]
Mainfest was updated in 2020: https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_245_AlleBlock

Without mark as obselete:

https://github.com/AdguardTeam/FiltersRegistry/blob/cc8550c77d0140907a5bfd655628cc77e1f11a68/filters/ThirdParty/filter_245_AlleBlock/metadata.json#L11-L16

> example:
> https://github.com/AdguardTeam/FiltersRegistry/blob/94bf0d705624e4e2004bee40cc3fc81940cd7874/filters/ThirdParty/filter_240_BarbBlock/metadata.json#L11-L13

**Comment by seba2282** [comment]
I understood. But author alleblock don't make to much to filter. So shouldn't be marked as obsolete?

**Comment by zloyden** [comment]
It's disabled for now. Thanks for letting us know about it.

**Comment by seba2282** [comment]
Welcome all Adguard Team

@maciejtarmas Look here and tell what about Alleblock? You will end him or continue?

**Comment by krystian3w** [comment]
https://www.instalki.pl/aktualnosci/internet/58293-allegro-nowa-strona-glowna-marzec-2023.html


https://www-instalki-pl.translate.goog/aktualnosci/internet/58293-Allegro-poluchil-novuyu-domashnyuyu-stranitsu.-Odni-budut-lyubit-yeye,-drugiye-budut-nenavidet-2023.html?_x_tr_sl=pl&_x_tr_tl=ru&_x_tr_hl=pl

**Comment by maciejtarmas** [comment]
> Welcome all Adguard Team
> 
> @maciejtarmas Look here and tell what about Alleblock? You will end him or continue?

I’m currently busy finishing other projects but thanks for reminding me. I’ll post an updated filter sometime late March/early April.
