### ISSUE TITLE
Wrongly use zh-CN for those phrases untranslated in zh-TW.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/FiltersRegistry#416]
Some filters' names and descriptions are wrongly used with Chinese Simplified if I keep them English on Crowdin.
Ex:
Online Malicious URL Blocklist
https://crowdin.com/translate/adguard-applications/17580/en-zhtw#3934122

Its description:
https://crowdin.com/translate/adguard-applications/17580/en-zhtw#3934124

zh-TW and zh-CN are different locales.
You shouldn't use zh-CN for those phrases untranslated in zh-TW.
Even English is better than Chinese Simplified for people who learn Chinese Traditional, Not Chinese Simplified.

**Comment by ameshkov** [comment]
It'd be better to translate them on Crowdin than to change how the fallback works.

**Comment by lancelot-moon** [comment]
Such like that I don't translate "AdGuard" to Chinese.
I think that not every filter name should be translated.
(BTW theirs descriptions can be translated.)

However, what I reported and translating are different things.
Ex: Will AdGuard app show Ukrainian translation in Russian interface if there is no Russian translation?
I bet it will show English when having no translation.
Simply, zh-TW and zh-CN are different locales, like those different locales, English, Russian, German...etc.

**Comment by ameshkov** [comment]
I agree that for some filter lists we should just keep the English name, but in this particular case it means that we should "translate" them on Crowdin to english versions.

**Comment by lancelot-moon** [comment]
@slavaleleka zh-TW is done. You can update filters registry until other locales are ready.

**Comment by lancelot-moon** [comment]
@slavaleleka 
You just added the descriptions for Xinggsf filter, Fanboy's Swedish, Fanboy's Vietnamese and Fanboy's Spanish/Portuguese 2 days ago.
Please update filters registry again.
Thanks.
