### ISSUE TITLE
Request for some filters

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/FiltersRegistry#42]
@ameshkov

1hosts.cf:
http://1hosts.cf/

CoinBlockerLists:
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/hosts

CoinBlockerLists (optional):
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_optional.txt

CoinMiner:
https://raw.githubusercontent.com/anudeepND/blacklist/master/CoinMiner.txt

NoCoin (adblock):
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt

NoCoin (hosts):
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt

Hexxium Creations Threat List:
https://raw.githubusercontent.com/HexxiumCreations/threat-list/gh-pages/hexxiumthreatlist.txt

Piperun's iplogger filter:
https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist

Ransomware Tracker Domain Blocklist:
https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt

AdZHosts:
https://adzhosts.fr/hosts/AdZGuardFilter.txt

B/R

**Comment by ameshkov** [comment]
We won't add hosts files

**Comment by ameshkov** [comment]
NoCoin is already there.

**Comment by ameshkov** [comment]
The only one that might be eligible:
https://raw.githubusercontent.com/piperun/iploggerfilter/master/filterlist

GH link: https://github.com/piperun/iploggerfilter

2 months without updates though. We'll keep an eye on it.

**Comment by ameshkov** [comment]
Filed a new issue about that filter:
https://github.com/AdguardTeam/FiltersRegistry/issues/46

**Comment by lancelot-moon** [comment]
I remember that AG for Android v3 can subscribe external filters...

Why can you not put some useful hosts files in default list for DNS filtering?

**Comment by ameshkov** [comment]
> I remember that AG for Android v3 can subscribe external filters...

Filters are not equal to hosts files.

Tbh, I don't like hosts files, the capabilities are too limited.

> Why can you not put some useful hosts files in default list for DNS filtering?

You mean like the "popular subscriptions" in AG for iOS?

**Comment by lancelot-moon** [comment]
Now, NoCoin is just in Content Blocker for Safari, not in ad blockers of AG for Android.

Why do you not also consider CoinMiner and CoinBlockerLists?

Ransomware Tracker Domain Blocklist can be for AG for Windows & macOS.

**Comment by lancelot-moon** [comment]
>You mean like the "popular subscriptions" in AG for iOS?

Yes, those hosts files are good while AG SDN filter is not enough.

**Comment by ameshkov** [comment]
> Now, NoCoin is just in Content Blocker for Safari, not in ad blockers of AG for Android.

Will be in v3.0

> Why do you not also consider CoinMiner and CoinBlockerLists?
> Ransomware Tracker Domain Blocklist can be for AG for Windows & macOS.

These are all hosts files.

> Yes, those hosts files are good while AG SDN filter is not enough.

Hosts files support for DNS filtering on Android makes sense indeed, but it has nothing to do with this repo.
