### ISSUE TITLE
Add EasyList Cookie

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#433]
No idea why we haven't done it earlier:
https://github.com/easylist/easylist/tree/master/easylist_cookie
https://secure.fanboy.co.nz/fanboy-cookiemonster.txt

**Comment by AdamWr** [comment]
If I'm not wrong, it's already added - https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_241_FanboyCookiemonster/metadata.json
