### ISSUE TITLE
Add ABClientFilters Korean

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/FiltersRegistry#446]
### Summary
Name: `ABClientFilters Korean`
Suggested tags: ~~`lang:ko purpose:ads obsolete`~~ ~~`lang:ko purpose:ads recommended`~~ `lang:ko purpose:ads`
Homepage: https://github.com/Pentanium/ABClientFilters/tree/master/ko

### Details
ABClientFilters Korean is aimed to block only ads.
At 2021-03-20T17:08:20Z, It blocks ads on main online community located in South Korea.
I will push many commits which block ads on most of the websites located in South Korea,

Cloud you please add this into AG's filter list?

**Comment by ameshkov** [comment]
Why `obsolete` tag? It does not seem obsolete to me:)

Also, could you please also supply a description?

**Comment by piquark6046** [comment]
> 
> 
> Why `obsolete` tag? It does not seem obsolete to me:)
> 
> Also, could you please also supply a description?

It had been looked that I must add `obsolete` tag because I thought "It does not have enough commits".
But, now, as you said, I think It does not need to add obsolete` tag.

Description:
```
This filter is optimized for blocking ads on many websites which are based on Korean language.
This is made by a global community which mainly located in GitHub.
```

**Comment by piquark6046** [comment]
@ameshkov 
Can I display AG's re-hosting link at `README.md` of ABClientFilters?

**Comment by ameshkov** [comment]
@piquark6046 sure, np

**Comment by ameshkov** [comment]
I have an issue with `recommended` though, the filter list is very new, enabling it for all Korean users right away looks too much to me.

**Comment by ameshkov** [comment]
@piquark6046 could you please also explain the difference with List-KR. Is your list supposed to be used alongside or is it a separate unrelated list? If so, what's wrong with [List-KR](https://github.com/List-KR/List-KR)?

**Comment by piquark6046** [comment]
> 
> 
> I have an issue with `recommended` though, the filter list is very new, enabling it for all Korean users right away looks too much to me.

Okay.

**Comment by piquark6046** [comment]
> 
> 
> @piquark6046 could you please also explain the difference with List-KR. Is your list supposed to be used alongside or is it a separate unrelated list? If so, what's wrong with [List-KR](https://github.com/List-KR/List-KR)?

Unlike List-KR, this filter blocks only ads on many websites which are based on Korean language.

**Comment by ameshkov** [comment]
@piquark6046 

1. Are they supposed to be used together?
2. Do you mean that List-KR misses some ads or that it blocks more than just ads?

**Comment by piquark6046** [comment]
> @piquark6046 
> 
> 1. Are they supposed to be used together?
> 2. Do you mean that List-KR misses some ads or that it blocks more than just ads?

1. I hope a user uses it without List-KR.
2. List-KR blocks not only ads but also tracker, anti-adblock and annoyances.
It means that options which a user can choose are decreased.

**Comment by piquark6046** [comment]
```
! Title: ABClientFilters Korean
! Description: This filter is optimized for blocking ads on many websites which are based on Korean language. It is made by a global community that are mainly located on GitHub. The global community recommends that use it with AG Base filter and AG Tracking Protection filter.
! Homepage: https://github.com/Pentanium/ABClientFilters/tree/master/ko
! License: https://github.com/Pentanium/ABClientFilters/blob/master/LICENSE
```

**Comment by ameshkov** [comment]
Got it, sorry for the late reply.

Here's what bothers me: we already have two lists for Korea and people tend to enable all filter lists they are getting. Adding a third one should be somehow justified. 

Also, here's a small checklist that needs to be done:

1. [ ] There should be a single filter list file, not a list of files. People should be able to use the list as a custom filter.
2. [ ] The repo should be properly decorated: README file with the detailed explanation of what this filter list is, how to report issues to it, etc.
3. [ ] Rules count (depending on the region, at least 200 rules for a regional  ad blocking list -- I guess you have no problem with this one).
4. [ ] We should be sure that the list will be maintained in the future and won't be a temporary thing. 
5. [ ] Usually, we only add lists that already have users that can recommend it.

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/FiltersRegistry/issues/446#issuecomment-810603544

- [x] There should be a single filter list file, not a list of files. People should be able to use the list as a custom filter. ( https://github.com/Pentanium/ABClientFilters/commit/4b4778223d8510d650fdc48dd3e3a756c11ab120 )
- [x] The repo should be properly decorated: README file with the detailed explanation of what this filter list is, how to report issues to it, etc. ( https://github.com/Pentanium/ABClientFilters/commit/893be501316f6dc76d8728af27c3d5f13f9a9acf )
- [x] Rules count (depending on the region, at least 200 rules for a regional ad blocking list -- I guess you have no problem with this one).
- [x] We should be sure that the list will be maintained in the future and won't be a temporary thing.
- [ ] Usually, we only add lists that already have users that can recommend it.

YousList is being followed ABP filter rules. This means that I cannot use advanced content blocking methods. (e.g. `#%#//scriptlet` and `#?#:upward()`)

When I contribute List-KR, Its owner allows me to use the advanced content blocking method. But, It blocks contents on web which may be useful for a visitor (e.g. Social sharing button)

**Comment by piquark6046** [comment]
The discussion is in progress...  https://github.com/List-KR/List-KR/discussions/199

**Comment by piquark6046** [comment]
This issue is solved.
