### ISSUE TITLE
Update AG_defineProperty to 1.0.4

### ISSUE THREAD

**Issue by theseanl** [AdguardTeam/FiltersRegistry#45]
A required js is contained in deep-override.min.js at https://github.com/AdguardTeam/deep-override/releases/tag/1.0.4

**Comment by ameshkov** [comment]
Guys, we need to be careful with this. Remember about FF and Opera, this will cripple rules that use `AG_defineProperty`. I suggest doing it right before releasing a patch for the browser extension next week.

**Comment by Alex-302** [comment]
done
