### ISSUE TITLE
add filter lists

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/FiltersRegistry#456]
bad IPs and domains list:
https://github.com/stamparm/ipsum/blob/master/levels/4.txt
https://github.com/stamparm/blackbook/blob/master/blackbook.txt

https://github.com/AdguardTeam/AdguardFilters/issues/80179#issue-855285048

**Comment by ameshkov** [comment]
FiltersRegistry is for content blocking lists, hosts lists better suite AdGuard Home.

Please take a look at this discussion:
https://github.com/AdguardTeam/AdGuardHome/issues/1913
