### ISSUE TITLE
add filter listssssss (content farm & fake news & antiscience...crazystuff )

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/FiltersRegistry#457]
content farm list:
https://github.com/FutaGuard/FutaFilter/blob/master/nofarm_hosts.txt
https://danny0838.github.io/content-farm-terminator/files/blocklist/content-farms.txt 
 ̶h̶t̶t̶p̶s̶:̶/̶/̶g̶i̶t̶h̶u̶b̶.̶c̶o̶m̶/̶w̶i̶l̶d̶s̶k̶y̶f̶/̶c̶o̶n̶t̶e̶n̶t̶-̶f̶a̶r̶m̶-̶l̶i̶s̶t̶/̶b̶l̶o̶b̶/̶m̶a̶s̶t̶e̶r̶/̶s̶r̶c̶.̶t̶x̶t̶
https://github.com/collaction/content-farm-blocker-android/blob/94e765a4452ecdedad691c8e0f711af41b3f2143/app/src/main/res/raw/site.txt

fake news list for hker, twese (and the people of mainland cn?):
https://github.com/festum/anti-bias-media/raw/master/ublacklist.txt #antifakenews_hongkong #antichinesemedia
https://github.com/c2xusnpq6/anticult_list/blob/main/adblocker.txt #antiantiscience #anticult

**Comment by c2xusnpq6** [comment]
https://chrome.google.com/webstore/detail/content-farm-terminator/lcghoajegeldpfkfaejegfobkapnemjl

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/114402714-b102f600-9bd6-11eb-9f2c-73f27cdb927e.png)

**Comment by DandelionSprout** [comment]
No way on earth would https://github.com/c2xusnpq6/anticult_list/blob/main/adblocker.txt be included, as it does nothing more than to target Falun Gong, which is also already heavily targeted by various PR-Chinese-maintained lists (Most notoriously *anti-AD*).

https://github.com/FutaGuard/FutaFilter/blob/master/nofarm_hosts.txt is already being considered: #430

https://danny0838.github.io/content-farm-terminator/files/blocklist/content-farms.txt is hampered by how adblockers no longer support `//` comments, which'd have to be removed before further inclusion consideration of it.

https://github.com/festum/anti-bias-media/raw/master/ublacklist.txt covers a pretty narrow topic for native inclusion, but I don't see any problems with it otherwise.

**Comment by c2xusnpq6** [comment]
bro! are you serious? Falun Gong?? that's is anti-science thing.... just like the korea thing.... the cult thing.......... whatever~ but don't del this issue! that's all~

**Comment by c2xusnpq6** [comment]
> ![image](https://user-images.githubusercontent.com/75058881/114402714-b102f600-9bd6-11eb-9f2c-73f27cdb927e.png)
> 

you may want to read this bro

**Comment by c2xusnpq6** [comment]
Falun Gong = antiscience ok? bro you good?

**Comment by c2xusnpq6** [comment]
I don't like that black guy, not because he's black person, because he did bad thing, and say something unreal, or... FAKE!! just like your "Falun Gong"......... bruh??! are you really ok bro? @DandelionSprout

**Comment by c2xusnpq6** [comment]
google "Falun Gong" and then click in any post they posted, you will realise that it's just like Jesus thing... but worse...

**Comment by c2xusnpq6** [comment]
you blocked me bro? haha wt* @DandelionSprout

very interesting~

**Comment by c2xusnpq6** [comment]
> Falun Gong = antiscience ok? isn't it?????? bro you good?😅🤦
> 
> (I hate CCP btFKINGw, but I don't want korea cult thing happen again... do you???) @DandelionSprout 

do you bro??? @DandelionSprout

**Comment by c2xusnpq6** [comment]
Norway can't see the news of korea cult thing? noFKINGway........ @DandelionSprout

**Comment by c2xusnpq6** [comment]
@DandelionSprout look at the title, hardly, and think, hardly, what's science, and what's isn't

I thought Norway is a country that make people say "WOW", and they believe on science, but I'm wrong, I guess.... @DandelionSprout

**Comment by c2xusnpq6** [comment]
@DandelionSprout look at the title, hardly, and think, hardly, what's science, and what's isn't

I thought Norway is a country that make people say "WOW", and they believe on science, but I'm wrong, I guess.... @DandelionSprout

**Comment by c2xusnpq6** [comment]
welcome to convince me......us that it has a positive effect on the world😃🤝

**Comment by ameshkov** [comment]
Hello,

We generally do not add filter lists that aren't related to content blocking (privacy, security, annoyances).

If people want to use those lists, they're free to add them as custom lists, but we'd like to keep the FiltersRegistry about content blocking.

**Comment by c2xusnpq6** [comment]
> Hello,
> 
> We generally do not add filter lists that aren't related to content blocking (privacy, security, annoyances).
> 
> If people want to use those lists, they're free to add them as custom lists, but we'd like to keep the FiltersRegistry about content blocking.

I know that sometimes it is difficult to define "fake news", but... content farm? is much simpler, right?...............😅🤔🤦

**Comment by c2xusnpq6** [comment]
> Hello,
> 
> We generally do not add filter lists that aren't related to content blocking (privacy, security, annoyances).
> 
> If people want to use those lists, they're free to add them as custom lists, but we'd like to keep the FiltersRegistry about content blocking.

I think those cults are easier to distinguish than "fake news", anti-science or make you do some crazy stuff (if you got some really really good reason, that's fine then) then you are "cult"? I guess?🤔🤔😵🤦

**Comment by ameshkov** [comment]
> but... content farm? is much simpler, right?

Could you please show a couple of examples?
