### ISSUE TITLE
Add CERT.PL's Warning List

### ISSUE THREAD

**Issue by antek821** [AdguardTeam/FiltersRegistry#466]
Please add Polish phishing list. It's a dynamically operating list that has been operating for over a year, aimed at users from Poland

Name: `CERT.PL's Warning List`
Tags: `lang:pl purpose:security`
Description in English: `Protect against to phishing. Created by CERT Polska`, Description in Polish: `Chroni przed phishing'iem. Lista tworzona przez CERT Polska`
Homepage: https://www.cert.pl/posts/2020/03/ostrzezenia_phishing/
Link to list: https://hole.cert.pl/domains/domains_adblock.txt

**Comment by krystian3w** [comment]
Allmost **online** hosts are aded into KAD: https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/ThirdParty/filter_232_KADPrzekrety at 3 times on day.

From KAD I and `hawkeye116477` remove CERT.pl hosts with expired WOH IS, blocked with error 403/404 once or twice a week.

If you must have 8+ updates at day maybe better add this as new project - AdGuard can run 24 updates cycles now and `ThirdParty` maybe have only 8 chances to detect new list.

**Comment by antek821** [comment]
@krystian3w thanks for the answer. I didn't know that KAD already had this list in it. Regarding what you wrote, I am closing the issue

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/FiltersRegistry/issues/666

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/HostlistsRegistry/issues/39
