### ISSUE TITLE
hblock 

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/FiltersRegistry#477]
hblock - Improve your security and privacy by blocking ads, tracking and malware domains.

https://github.com/hectorm/hblock

https://hblock.molinero.dev/

https://hblock.molinero.dev/hosts_adblock.txt

https://hblock.molinero.dev/hosts_domains.txt

https://hblock.molinero.dev/hosts

**Comment by ameshkov** [comment]
We don't add hostlists here. You probably need to suggest them here: https://github.com/AdguardTeam/AdGuardHome/issues/1913
