### ISSUE TITLE
Phishing Army

### ISSUE THREAD

**Issue by c2xusnpq6** [AdguardTeam/FiltersRegistry#478]
Phishing Army | The Blocklist to filter Phishing! https://phishing.army/

Generated every 6 hours from PhishTank,
OpenPhish, Cert.pl and PhishFindR reports.
Each domain is analyzed to eliminate false positives,
through the Whitelist of Anudeep and the Alexa Rank.

https://phishing.army/download/phishing_army_blocklist.txt

https://phishing.army/download/phishing_army_blocklist_extended.txt

**Comment by ameshkov** [comment]
Again, pretty restrictive license
