### ISSUE TITLE
new list -> blocklists-main

### ISSUE THREAD

**Issue by scafroglia93** [AdguardTeam/FiltersRegistry#493]
My personal list kept with the definitions of the various researchers and / or companies

Source ->
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-main.txt

**Comment by ameshkov** [comment]
Looks like a hosts blocklist.

Here in this repo we only add blocklists for browser blockers. However, your list may fit the AdGuard Home vetted hosts blocklists: https://github.com/AdguardTeam/AdGuardHome/issues/1913
