### ISSUE TITLE
new list -> blocklists-certego

### ISSUE THREAD

**Issue by scafroglia93** [AdguardTeam/FiltersRegistry#495]
list that I generate following the releases of the certaingo bot via twitter

Source ->
https://twitter.com/certego_intel

Source ->
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-certego.txt

**Comment by ameshkov** [comment]
Please see this response: https://github.com/AdguardTeam/FiltersRegistry/issues/493#issuecomment-861291252
