### ISSUE TITLE
false positive (important)

### ISSUE THREAD

**Issue by saurane** [AdguardTeam/FiltersRegistry#515]
This is required to watch tv live broadcasts. If you block this, you will not be able to watch the live broadcast.
Please remove from list. "" ipcheck.tmgrup.com.tr ""
Live broadcast address: https://www.atv.com.tr/canli-yayin

Available on these lists: AdGuard tracking protection filter, Energized, Goodbyads
Fixed: 1Hosts, AdGuard DNS filter, notracking, oisd

**Comment by Alex-302** [comment]
It was fixed 3 days ago in https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/727
