### ISSUE TITLE
Translate descriptions for few Dandelion Sprout's filter lists

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/FiltersRegistry#541]
descriptions for `Dandelion Sprout's Annoyances List` and `Legitimate URL Shortener` are not translated for now

**Comment by slavaleleka** [comment]
we have such descriptions

− `Dandelion Sprout's Annoyances List` :
`This list is made in the style of AdGuard's and Fanboy's annoyances lists. It combines many of Dandelion Sprout's proudest and most frequently maintained international lists, as a curated compilation for simplicity's sake.`

− `Legitimate URL Shortener` :
`In a world dominated by bit.ly, ad.fly, and several thousand other malware cover-up tools, this list reduces the length of URLs in a much more legitimate and transparent manner. Essentially, it automatically removes unnecessary '$' and '&' values from the URLs, making them easier to copy from the URL bar and pasting elsewhere as links.`

I think they are a bit long and not really clear for user

@DandelionSprout could you please describe the purpose of these lists considering why they could be useful for regular users?

**Comment by DandelionSprout** [comment]
Those descriptions are almost 1:1 with the in-list `! Description:` values, so this request took me a bit by surprise tonight.

**Comment by slavaleleka** [comment]
so you agree to leave as they are?

**Comment by slavaleleka** [comment]
@DandelionSprout 
these strings are available for translating on crowdin now

**Comment by iam-py-test** [comment]
@DandelionSprout I believe there is a typo. The domain is `adf.ly` not `ad.fly`, as the former exists and the latter does not
