### ISSUE TITLE
Android app crashes [E-devlet]

### ISSUE THREAD

**Issue by saurane** [AdguardTeam/FiltersRegistry#544]
Android app: E-devlet (Turkish government app)
Subdomain: analitik.edevlet.gov.tr
Client: NextDNS
When this subdomain is blocked, the application gives an error. Please remove from the list.

## LIST
https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_3_Spyware/filter.txt

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdGuardSDNSFilter #836](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/836) via [**ZenHub**](https://www.zenhub.com/)
