### ISSUE TITLE
:matches-css (regex flags)

### ISSUE THREAD

**Issue by realodix** [AdguardTeam/FiltersRegistry#545]
Looks like AdGuard doesn't support regex flags for `:matches-css()`. I didn't notice until I saw https://github.com/AdguardTeam/AdguardFilters/issues/101083 and read the [documentation](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#pseudo-class-matches-css), because in the diff.txt file there is no message.

```html
<style type="text/css">
  #to-be-blocked::before {
    content: "Advertisement"
  }
</style>
<div id="to-be-blocked" class="banner"></div>
<div id="not-to-be-blocked" class="banner"></div>
```

`##div.banner:matches-css-before(content: /adv/i)`

uBO requires using the `i` flag to be case insensitive.

https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectmatches-cssarg

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/ExtendedCss #138](https://github.com/AdguardTeam/ExtendedCss/issues/138) via [**ZenHub**](https://www.zenhub.com/)
