### ISSUE TITLE
Barblock

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/FiltersRegistry#546]
@alhambra11 commented on [Sat Nov 27 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1910)

I'm running the beta version of adguard for chrome, and I see Barblock list is still here. Since it's not maintained anymore, wouldn't be better to get rid of it?

**Comment by ameshkov** [comment]
Is it really not maintained or is there nothing to add?

**Comment by zloyden** [comment]
Hm, last update was in 2019. I think we can consider it obsolete.
