### ISSUE TITLE
New possible filters?

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/FiltersRegistry#547]
@alhambra11 commented on [Sat Nov 27 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1909)

Since Spam404 project was discontinued, could we have an optional anti-phishing list? Ideally I'd suggest https://gitlab.com/curben/phishing-filter it's from the same author of the already in-built malware URL blocklist. Additionally, there's another small list to use to stave off PUPs https://gitlab.com/curben/pup-filter

Both of these already come fully compatible for both adguard home and adguard browser extension. Adding them to the android version would be a great addition imo.

**Comment by zloyden** [comment]
> if there is a repository on GitHub, the number of stars should be at least 50
if there is no repository on GitHub, the number of analyzed issues and discussions is estimated at 10 per month on the filter's website

Hi @alhambra11! Actually, I'd add them, if they were more popular. Please read our rules for adding filters [here](https://github.com/AdguardTeam/FiltersRegistry#what-filters-can-be-added-to-this-repository).

> Both of these already come fully compatible for both adguard home and adguard browser extension.

I've seen this and it's nice :)
