### ISSUE TITLE
Add IndianList

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/FiltersRegistry#550]
* https://easylist-downloads.adblockplus.org/indianlist.txt

Although its maintainer (MediumKreation) has little communication with the rest of the adblocker community, we've got little choice but to take the list seriously when it has ≥7,000 entries, is updated 40 times a week, and is the *only* known active list for all *13* of the languages it covers.

**Comment by krystian3w** [comment]
If this is not mirror fanboy project with changed heading: https://github.com/AdguardTeam/FiltersRegistry/issues/250

**Comment by DandelionSprout** [comment]
I think the list differs strongly from Fanboy's Indian, but I can doublecheck later tonight or tomorrow.

**Comment by krystian3w** [comment]
I suppose Fanboy cover North America pages instead like that form issue try cover south Asia pages.

**Comment by DandelionSprout** [comment]
A quick comparison of the two lists, tells me that there is zero overlap between the two lists, as every single entry is unique.

To further show that Fanboy has nothing to do with IndianList: https://github.com/mediumkreation/IndianList

**Comment by krystian3w** [comment]
But you don't checked what language cover Fanboy, maybe https://www.britannica.com/topic/North-American-Indian-languages

**Comment by DandelionSprout** [comment]
One can easily tell from https://fanboy.co.nz/fanboy-indian.txt that it does not cover Native American, First Nations nor Amerindian languages.

**Comment by krystian3w** [comment]
So you must start promote in Poland term "Amerindian" intead "Indianin".

**Comment by gwarser** [comment]
@krystian3w general consensus is: you need to fix your translator.

**Comment by krystian3w** [comment]
I do not use translator in that topic.

I use my brain to create setence equivalent ("równoważniki zdania").

**Comment by zloyden** [comment]
Hi! This will be discussed here https://github.com/AdguardTeam/FiltersRegistry/issues/608
