### ISSUE TITLE
Improve description for `KAD - Anti-Scam` filter subscription

### ISSUE THREAD

**Issue by adbuker** [AdguardTeam/FiltersRegistry#552]
As is: `Filter that protects against various types of scams, such as mass text messaging, fake online stores, etc.`
To be: `Filters protecting against various threats in the Polish network, such as viruses, fake stores and SMS subscriptions. In addition, they contain entries created by CERT Polska, legalniewsieci.pl, KNF and other teams.`. The description should be similar to the original description, specifying that this subscription first of all relevant to the Polish language

**Comment by el-termikael** [comment]
Let's rewrite it this way:

Filter that protects against various types of scams in the Polish network, such as mass text messaging, fake online stores, etc. It contains rules created by CERT Polska, KNF, legalniewsieci.pl, and other filter developers.

**Comment by el-termikael** [comment]
A shorter version: Filter that protects against various types of scams in the Polish network, such as mass text messaging, fake online stores, etc.

**Comment by krystian3w** [comment]
Also possible update URL-s to correct use `/FiltersHeroes/`

**Comment by zloyden** [comment]
> Also possible update URL-s to correct use `/FiltersHeroes/` based on older commit [61965c5](https://github.com/AdguardTeam/FiltersRegistry/commit/61965c5782aa789b35145228cf2b6ec930736e46)

I partly agree with you, but the current site `https://kadantiscam.netlify.com/` are available.

**Comment by krystian3w** [comment]
I mean change link from this repo copy rules - 8 times at day, now link works due Github mirroring to oldie name of organisation.

**Comment by zloyden** [comment]
Well, we can do that. I can also change `homepage` - this will be related to that subscription link.
