### ISSUE TITLE
New NSFW filter from My Privacy DNS

### ISSUE THREAD

**Issue by spirillen** [AdguardTeam/FiltersRegistry#554]
As we are hunting for adware/spyware etc, then one of the "places" we are using are NSFW sites, as a bi product we build and maintain the [Porn Records project](https://mypdns.org/my-privacy-dns/porn-records) (The master)

### Proposed solution

We have today setup the script to also generate 2 lists for ad-blockers

1. Ordinary Adult mainstream sites
2. A very strict one for which users should be prepared to maintain there own whitelist, as there are no mercy, if the domain hosts a significant amount of porn, well it is on this list.
    As example to this is `*.bp.blogspot.com` the fact is, this is among the biggest porn CDN's

### Additional information

To build and host the active only records we have fully integrated the well known `clefspeare13/pornhosts` with our previously mentioned Porn Records, as announce a long time ago, but the process have been speed up do to Github's take down of https://github.com/clefspeare13/pornhosts

The lists we hope is fulfilling the requirement to be useful within AdGuardHome should be located at:

- https://mypdns.org/clefspeare13/pornhosts/-/blob/master/download_here/ad_blockers/ad_blockers.filter
- https://mypdns.org/clefspeare13/pornhosts/-/blob/master/download_here/strict/ad_blockers/ad_blockers.strict

**Tip**: for downloading these files you replace `/blob/` in the urls with `/raw/`

I'm looking forward to some useful replies, is the lists actually is useful to you?, is there lacking some improvements etc.

**Comment by ameshkov** [comment]
@AdguardTeam/filters-maintainers guys, we're going to publish a new repo soon specifically for DNS filter lists. AdGuard DNS filter will be also moved there.

**Comment by spirillen** [comment]
> @AdguardTeam/filters-maintainers guys, we're going to publish a new repo soon specifically for DNS filter lists. AdGuard DNS filter will be also moved there.

Hey @ameshkov 

Thanks for your reply... If I understand this correct, then you are going to start a new sub repo to https://github.com/AdguardTeam which in somehow should support DNS filter, right?

Now it my very question, which format do you have in mind?

Bind style? RPZ DNS style? Will it support wildcard blacklisting on only the dumb old hosts style?

Is it possible a could have a peak at some of these threats :candy: so if I think is would be a better match could rewrite my scripts to match the new repo?

**Comment by ameshkov** [comment]
> Thanks for your reply... If I understand this correct, then you are going to start a new sub repo to https://github.com/AdguardTeam which in somehow should support DNS filter, right?

> Now it my very question, which format do you have in mind?

Just like FiltersRegistry, the idea is to re-host the existing filter lists on our servers so that we could react on any unexpected changes promptly.

We'll support filter lists in the same formats that are supported by [AdGuard products](https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists).

However, most likely, we'll convert them to adblock-style automatically using https://github.com/AdguardTeam/HostlistCompiler

**Comment by spirillen** [comment]
Thanks for the reply, I will get back to this one later. Is i do not use hosts formatted files.... (they are only there for Pi-hole)
