### ISSUE TITLE
Migrating from NeatURL (missing AliExpress et.al.)

### ISSUE THREAD

**Issue by maricn** [AdguardTeam/FiltersRegistry#559]
I'm moving away from using NeatURL to your filter17, however I found some useful URL tracking `removeparams` filters are not present in your filter file.

For instance, NeatURL has:
```
spm@*.aliexpress.com, scm@*.aliexpress.com, aff_platform, aff_trace_key, algo_expid@*.aliexpress.*, algo_pvid@*.aliexpress.*, btsid, ws_ab_test
```

**Comment by ameshkov** [comment]
@AdguardTeam/filters-maintainers guys, could you please take a look?

**Comment by Alex-302** [comment]
It seems following rules do not break anything:
```
||taobao.com^$removeparam=scm
||taobao.com^$removeparam=pvid
||taobao.com^$removeparam=utparam
!
||aliexpress.com^$removeparam=spm
||aliexpress.com^$removeparam=scm
||aliexpress.com^$removeparam=scm_id
||aliexpress.com^$removeparam=scm-url
||aliexpress.com^$removeparam=utparam
```
not sure about all othere parameters. Some added by cashback services.

**Comment by maricn** [comment]
just for completeness, i found https://github.com/DandelionSprout/adfilt having an exhaustive list of related `removeparam` rules..

**Comment by Alex-302** [comment]
@maricn No need to remove literally all parameters.

**Comment by zloyden** [comment]
> No need to remove literally all parameters.

Yep, it's a dangerous practice.
