### ISSUE TITLE
[enhacement] CoinBlockerLists

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#56]
@FadeMind commented on [Tue May 29 2018](https://github.com/AdguardTeam/AdguardForWindows/issues/2226)

Hello Adguard Developers

Please consider adding to available list in Adguard For Windows:
**CoinBlockerLists** - massive coin minner blacklist.

Basic Description data:
```
! Description: This list disables browser based miners such as coin-hive
! Title: CoinBlockerLists by ZeroDot1 uBlock / This list disables browser based miners such as coin-hive
! Version: Continuous
```

License: GNU Affero General Public License v3.0 
Homepage: https://github.com/ZeroDot1/CoinBlockerLists
Blocklist Rules: 
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

or

https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser_UBO.txt

CC @ameshkov @zerodot1

**Comment by lancelot-moon** [comment]
Hi,
Why to use the mini list for only browsers (only domains)?
I prefer the complete list for system-wide blocking.

This list contains all domains - A hostslist for administrators to prevent mining in networks:
https://zerodot1.github.io/CoinBlockerLists/hosts

This list contains all optional domains - An additional hostslist for administrators:
https://zerodot1.github.io/CoinBlockerLists/hosts_optional

And then you can add CoinMiner.
https://github.com/anudeepND/blacklist
https://raw.githubusercontent.com/anudeepND/blacklist/master/CoinMiner.txt

I early used them in AG Pro for iOS.
Honestly, you will say they're hosts files. (Include the topic by FadeMind.)
In the past, I already suggested to add them in the known list for future AdGuard.
https://github.com/AdguardTeam/FiltersRegistry/issues/42

**Comment by ZeroDot1** [comment]
@lancelot-moon @ameshkov  Thanks for using the coiunBlockerLists.
The anudeepND blacklist looks like an old outdated version of the CoinBlockerLists.
You can find the homepage of the CoinBlockerLists at the following link: https://zerodot1.github.io/CoinBlockerListsWeb/index.html

**Comment by lancelot-moon** [comment]
I don't understand why you don't choose the complete list.
This list contains all domains - A list for administrators to prevent mining in networks
https://zerodot1.github.io/CoinBlockerLists/list.txt

And then you just chose list_browser.txt.
This list contains all browser mining domains - A list to prevent browser mining only
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

The domains in list_browser.txt are also in the complete list...

**Comment by FadeMind** [comment]
@ameshkov @ZeroDot1 

See this https://gitlab.com/ZeroDot1/CoinBlockerLists/issues/1

Please prepare and add to Adguard valid with ADG coin blocklist based on
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt
(all domains) as @lancelot-moon  said. 
Thanks

**Comment by superlex** [comment]
It looks like it doesn't exist anymore:
https://github.com/ZeroDot1/CoinBlockerLists

**Comment by FadeMind** [comment]
@superlex  https://gitlab.com/ZeroDot1/CoinBlockerLists

Adguard Devs have issue with AGPL license. Thats why CBL is not added officially.

**Comment by superlex** [comment]
Thank you @FadeMind ;)

PS:
Hello @ZeroDot1 :)

**Comment by ZeroDot1** [comment]
Hi @superlex,
If you have any questions, please let me know.
For more details about the CoinBlockerLists please have a look at the CoinBlockerLists Homepage.
https://zerodot1.gitlab.io/CoinBlockerListsWeb/index.html

**Comment by zloyden** [comment]
If still relevant, write in this task.

**Comment by zloyden** [comment]
@TPS as I can see, the lists are based on hosts, so better to file an issue here https://github.com/AdguardTeam/HostlistsRegistry.

**Comment by TPS** [comment]
@zloyden If so, could you move the issue there officially?  Though, I _do_ see [1 adblock-formatted subscription](https://zerodot1.gitlab.io/CoinBlockerLists/list_browser_UBO.txt) there.

**Comment by zloyden** [comment]
> If so, could you move the issue there officially?

Sure, it is here https://github.com/AdguardTeam/HostlistsRegistry/issues/64 now.

> Though, I do see [1 adblock-formatted subscription](https://zerodot1.gitlab.io/CoinBlockerLists/list_browser_UBO.txt).

Wide rules. Should be rewritten like `||example.org^$third-party`.

**Comment by TPS** [comment]
@zloyden If so, could you move the issue there officially?  Though, I _do_ see [1 adblock-formatted subscription](https://zerodot1.gitlab.io/CoinBlockerLists/list_browser_UBO.txt) there.

Yes, I just filed an issue there to fix that.
