### ISSUE TITLE
Add EasyList Thailand and make it the default filter for Thai language

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/FiltersRegistry#580]
Citing verbatim from another person's statements in https://github.com/AdguardTeam/AdguardFilters/issues/110070 due to the new anti-stale rule there:

*"When I visit a website in Thai, Thai Ads Filters are automatically enabled. However, this is not a good choice. Because this filter is not maintained for a long time. Currently, the most popular filter in Thailand is EasyList Thailand (https://raw.githubusercontent.com/easylist-thailand/easylist-thailand/master/subscription/easylist-thailand.txt). This filter is also the default in uBlock Origin. Therefore, I request that the standard Thai filter in AdGuard be changed to EasyList Thailand."*

**Comment by zloyden** [comment]
As I can see, this filter got last update `15.11.2021` and there are also no open issues.
However, we can try it if it's popular in Thailand.
@DandelionSprout what do you suggest for `description`?

**Comment by DandelionSprout** [comment]
By running https://github.com/easylist-thailand/easylist-thailand/#easylist-thailand through Google Translate and then doing minor grammar improvements on the translated output, I propose *"Helps you block all advertisements on various websites in Thailand"* as the description.

**Comment by zloyden** [comment]
This filter `EasyList Thailand` is recommended now.
