### ISSUE TITLE
Keep original names and improve descriptions for third-party filters

### ISSUE THREAD

**Issue by DA-FormMaker** [AdguardTeam/FiltersRegistry#607]
Вот отсюда https://filterlists.com/ был установлен фильтр **EasyList China**

<details><summary>Screenshot:</summary>

![2022-04-15_18-06-57](https://user-images.githubusercontent.com/101049895/163590042-0ded621d-3b39-42e1-9f85-43e9b62e2c7b.png)

</details><br/>

Почему в столбце с название фильтра он прописан как **EasyList Китайский**?

Зато вот здесь подобного не наблюдается

<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/101049895/163590658-8f6e7633-7885-404d-b62a-c3a04ecdffdf.png)

</details><br/>

Если брать верхний пример как за основу, то в столбце с название фильтра он должен быть прописан как **RU AdList: Счетчики** ( но вместо этого он прописан как **RU AdList: Counters** )

Не понятно как **AdGuard** определяет когда и на каком языке прописывать текст?

**EasyList China - EasyList Китайский** и **RU AdList: Counters - RU AdList: Счетчики**

Почему при одинаковых обстоятельствах **AdGuard** ведет себя по разному?

**Comment by slavaleleka** [comment]
we will keep the original filters names and improve descriptions a bit
