### ISSUE TITLE
Add mediumkreation's Indian list

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/FiltersRegistry#608]
`https://github.com/mediumkreation/IndianList`
The list has been well-maintained for long time now.

**Comment by DandelionSprout** [comment]
Probably a duplicate of #550, but I approve of this re-posting if it speeds up the addition process.

**Comment by zloyden** [comment]
According to our rules, this repo doesn't have enough stars. Nevertheless, I suppose we can add it.

**Comment by DandelionSprout** [comment]
A fair few of the repo's rules have struck me as odd for some time now, especially the "10 updates per month" rule. So I guess many of the rules can be bypassed, especially for regional lists.

**Comment by Yuki2718** [comment]
> Probably a duplicate of 

Oh, sorry I forgot to check.
