### ISSUE TITLE
Consider excluding t.co blocking

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/FiltersRegistry#619]
Though it's certainly against the maintainer's intention (@pgl), it's now clear too many people don't understand what's happenning. See https://github.com/AdguardTeam/AdguardFilters/issues/120068

**Comment by pgl** [comment]
Define "too many people"

**Comment by Yuki2718** [comment]
You know, that's not strictly provable - but it's not only the issue, I see the same complaints on Japanese anonoymous blocking board and on Twitter too.

**Comment by pgl** [comment]
Yeah sorry - my point is, "too many" is subjective really. 1 person could be too many, or 100,000 might *not* be too many, depending on how strict you want to be.

**Comment by Yuki2718** [comment]
And that's why I opened an issue with the title "Consider" instead of PR I usually do here. I'm sure AG members are aware of this but still wanted to prompt them that some user are getting trouble. If I understand correctly, Safari CB doesn't give any clue about blocking.

**Comment by pgl** [comment]
Sure, and credit for the issue title - just a minor point about the *content* of the issue. :)

**Comment by Yuki2718** [comment]
Essentailly I'm suggesting badfiltering your rule in AG lists like done in uAssets. TBH uBO has better UI for that than AG Content blocker, and actually many of those are from iOS user.

**Comment by ameshkov** [comment]
Hmm, Peter's list is not default in AdGuard. People must enable it manually to get their Twitter broken 😄 

Could rename it to `Peter Lowe's List (breaks Twitter)` 🤔 

> TBH uBO has better UI for that than Safari Content blocker, and actually many of those are from iOS user

Yup, Safari thinks block page is lame and simply shows an error.

Regarding badfiltering, if it really creates lots of reports, let's do it then.

**Comment by pgl** [comment]
If the title were `Peter Lowe's List (breaks Twitter unless you don't mind their tracking)` then I'd be all for that. Bit wordy though.

**Comment by Yuki2718** [comment]
> Regarding badfiltering, if it really creates lots of reports, let's do it then.

So far I don't say it's too many.

**Comment by ameshkov** [comment]
As I see the only reports we're getting are from iOS and Safari, let's add a `$badfilter` for these two platforms only.
