### ISSUE TITLE
add polish supplement list

### ISSUE THREAD

**Issue by KonoromiHimaries** [AdguardTeam/FiltersRegistry#62]
https://github.com/MajkiIT/polish-ads-filter/issues/7904#issuecomment-394681505

add "Polish Social Filters - Supplement for uBlock & AdGuard"

<code>https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/adblock_social_filters/social_filters_uB_AG.txt</code>

add "Polish Annoyance Filters - Supplement for uBlock & AdGuard"

<code>https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB_uBlock_AdGuard.txt</code>

**Comment by ameshkov** [comment]
We are about to add the `#include` directive support. Once it's done, there will be no need to have supplement filters anymore.
