### ISSUE TITLE
Gambling Filterlist?

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/FiltersRegistry#630]
Could a proper gambling/betting/lottery block/filterlist be added/developed?  I've searched high & low, but keep finding solely `hosts`/domain-based lists, which _don't_ help in the case of such integrated on other sites (e.g., "Latest Sports Betting" section on https://nypost.com/2022/06/21/amazon-prime-day-devices-deals-up-to-55-off-echo-ring/).

**Comment by zloyden** [comment]
Doesn't quite fit the filters. More like parental control either here https://github.com/AdguardTeam/HostlistsRegistry.

**Comment by TPS** [comment]
Again, could this be moved there officially?
