### ISSUE TITLE
Split AdGuard Annoyances filter 

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/FiltersRegistry#632]
Split AdGuard Annoyances filter into few new filters for different purposes (chat widgets, cookies, etc.). So AdGuard Annoyances filter should be a combination of new separated filter

**Comment by ameshkov** [comment]
@slavaleleka I think I've already created an issue about that (maybe in the AdguardFilters repo?).

@AdguardTeam/filters-maintainers by any chance, do you remember that issue or was it just a discussion in Slack?

**Comment by BlazDT** [comment]
Only remember slack discussion.

**Comment by ameshkov** [comment]
Here's what I suggest:

1. Keep the Annoyances filter as a union of all smaller filters and reflect it in the filter description.
2. We should also change the directories structure in the AdguardFilters repo.
3. The categories were already discussed in Slack once, but it is probably already lost.

Here're the categories I think make sense:

1. Cookie notices.
2. Pop-ups in general (including social, news subscriptions, adblock circumvention stuff).
3. Online assistants (flashy support widgets mostly).
4. Mobile app banners (should include the `$$link` rule that disables PWA).

What else?

Assigned to @zloyden. Please tell me what you think and what changes you would like to introduce.

Please note, that these filters will be available in the apps UI as separate checkboxes so let's take this seriously.

**Comment by zloyden** [comment]
Before do that, we have to talk about the new categories, the filter names, the descriptions, what they will include.
Actually, I would leave AdGuard Annoyances as is, add new filters based on AdGuard Annoyances sections and our discussions.
