### ISSUE TITLE
"redirect:" in "exclusions.txt" is too broad

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/FiltersRegistry#636]
`redirect:` in https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/exclusions.txt seems to cause the incorrect exclusion of `##.mob-app-redirect:not(html, body)` in Dandelion Sprout's Annoyances List, which I've had to change to simply `##.mob-app-redirect` in the meantime.

**Comment by ameshkov** [comment]
@zloyden do we still need it?

**Comment by zloyden** [comment]
I'm not sure that we need this.

**Comment by zloyden** [comment]
@DandelionSprout you can revert your rule in 1-2 hours.
