### ISSUE TITLE
Decrase expires of List-KR

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/FiltersRegistry#652]
I think that 4 days, interval of the filter update, is too long because activity of List-KR has been increased since few months ago.

So, Can you decease from 4 days to 2 days or lower?

Related Commit:
 - https://github.com/AdguardTeam/FiltersRegistry/commit/cd4ad9382dab851d1d7cf8964473305265a0635c

**Comment by zloyden** [comment]
I understand that, but we'll leave it as it is for now.
