### ISSUE TITLE
Add new security blocklist by CERT Poland

### ISSUE THREAD

**Issue by Dojexbeh** [AdguardTeam/FiltersRegistry#666]
There’s link to List of malicious domains created and updated on fly by CERT Poland:

-format compatible with browser extensions: Adblock Plus, uBlock Origin, Adguard: https://hole.cert.pl/domains/domains_adblock.txt

-hosts format: https://hole.cert.pl/domains/domains_hosts.txt

On this site https://cert.pl/en/posts/2020/03/malicious_domains/ are available more information, description and also other formats of this list.

Please add to AdGuard-DNS.

In my opinion this malicious and fraud blocklist is important for polish users of AdGuard-DNS because hardening and improve network security as well.

**Comment by krystian3w** [comment]
Duplicate of #466

**Comment by krystian3w** [comment]
Polish KAD **don't disabled** import new domains at 4 tries on 4 hours delay.

**Comment by Dojexbeh** [comment]
But KAD list is implemented only in AdGuard Home and Adguard on iOS, Android and not is implemented in Adguard-DNS.io - am I wrong ?
I

**Comment by Dojexbeh** [comment]
But KAD list is implemented only in AdGuard Home and Adguard on iOS, Android etc. - and not is implemented in Adguard-DNS.io - am I wrong ?
