### ISSUE TITLE
Could scriptlets from `road-block lite` be allowed?

### ISSUE THREAD

**Issue by sugarfreesweetener** [AdguardTeam/FiltersRegistry#669]
https://github.com/tcptomato/ROad-Block/blob/master/road-ubo.txt is included in `road-block lite`

**Comment by zloyden** [comment]
I guess we can do that.

> included in road-block lite

It looks like they are separated.

**Comment by zloyden** [comment]
Allowed scriptlets in the filter, update will be available today in some time.
