### ISSUE TITLE
Auto-build stopped at Fri Oct 14 17:29:59 UTC 2022

### ISSUE THREAD

**Issue by antek821** [AdguardTeam/FiltersRegistry#676]
Please check why last build is from yesterday.

Because of this, AdGuard can't update the built-in lists

**Comment by antek821** [comment]
@Alex-302 @slavaleleka @ameshkov @zloyden 
Can you check what the problem is?

**Comment by ameshkov** [comment]
Thanks for pinging us about that!

**Comment by antek821** [comment]
@ameshkov Thank you for fixing the problem over the weekend. I really appreciate it :smile:

**Comment by antek821** [comment]
@ameshkov some problems again. Last build: `skip ci. build from Wed Nov 2 07:33:28 UTC 2022`

**Comment by ameshkov** [comment]
Looking into it, thank you!
