### ISSUE TITLE
Add a new group of filters ("hosts filters")

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#68]
There are quite a few domain-level filters we are ignoring because they don't use the "adblock" syntax:
https://github.com/AdguardTeam/FiltersRegistry/issues/42

Examples:

* http://1hosts.cf/
* CoinBlockerLists
* adaway filters
* etc, etc
* see this also: https://github.com/AdguardTeam/FiltersRegistry/issues/68

Instead of ignoring them we could do the following:

1. Mark them with a special tag (`hosts`)
2. Convert them into the adblock syntax automatically

We will need to enhance filters-compiler so that it was able to do the conversion.

We will then be able to list these filters in the "privacy subscriptions"  of the iOS app, and in the DNS filters in the Android app.

**Comment by ameshkov** [comment]
@lancelot-moon the filters you requested may land here in the end:)

**Comment by lancelot-moon** [comment]
I start to think you're like a wishing machine.
Sorry if bothering you.

I don't know how you will design the subscriptions of AG for Android v3.
As a user, I wish AG for Android v3 will allow to separately subscribe filters for HTTPS filtering and for DNS filtering by URL.

I mean 2 zones of subscriptions.
For HTTP(S) filtering:
(supported formats: basic & advanced adblock rule syntax)
AdGuard Base filter
AdGuard Mobile Ads filter
Piperun's iplogger filter
...etc.

For DNS filtering when enabling DNS setting and allow DNS requests blocking:
(supported formats: domains, hosts file, basic adblock rule syntax and even ip)
AdGuard SDN filter
http://1hosts.cf/
CoinBlockerLists
AdZHosts
...etc.

Of course, if AdGuard will put some good filters in the known list, it's good and thoughtful.

Thanks a lot!

**Comment by lancelot-moon** [comment]
@ameshkov 
https://github.com/collinbarrett/FilterLists/issues/539
Badmojr just updated his 1hosts.cf.
Complete list = addon + mini list
He added graph.facebook.com and some domains which may break pages in the complete list.

I think it's better to only use the mini list.
Mini list:
The mini list is suitable to most users.
hosts file:
https://1hosts.cf/mini/

Only domains format:
https://1hosts.cf/mini/list.txt

Thanks.

**Comment by lancelot-moon** [comment]
1Hosts website's domain is frequently down.
Please use the link of 1Hosts (mini) from GitHub.
https://github.com/badmojr/1Hosts/tree/master/mini

**Comment by lancelot-moon** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1357
Chinese ad domains list:
https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt

**Comment by ameshkov** [comment]
Yeah, with how it goes we will soon have to finally implement this task.

I'd also like to split AdGuard SDN filter list into smaller parts (ads, privacy, etc, etc).

**Comment by balupton** [comment]
These dotfiles https://github.com/bevry/dotfiles have [a `select-hosts` command](https://github.com/bevry/dotfiles/blob/e1a4fd72b12bf3f9cf2200029a441b81c5838569/commands/select-hosts) to make selecting and apply hosts files easy.
