### ISSUE TITLE
Add the No more Qanon filter to Private DNS filter list

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/FiltersRegistry#681]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

Requested by:

CRM ID 678033

### Proposed solution

Add the filter, so users could subscribe to it; it contains over 2000 rules, so it cannot be imported to the user rules section due to the limitations we've set

Link: https://github.com/rimu/no-qanon/blob/master/adblock.txt

**Comment by ameshkov** [comment]
There's a separate repo for such requests:
https://github.com/AdguardTeam/HostlistsRegistry

It'd be better if the user makes this request personally (and check the repo rules before making a request).

**Comment by Alex-302** [comment]
@ameshkov Is not it a censorship filter?
