### ISSUE TITLE
Make included lists able to use `$inline-script`

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/FiltersRegistry#683]
### Prerequisites

- [X] This problem is not related to filtering issues. Otherwise, you should read this [article](https://kb.adguard.com/technical-support/reporting-tool);
- [X] You're using an up-to-date version of the problematic filter;

### Problem description

`$inline-script` in https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/exclusions.txt is causing problems for me on `https://www.15min.lt/naujiena/aktualu/lietuva/v-rupsys-apie-raketos-smugi-lenkijoje-sudetinga-buti-pasiruosus-sureaguoti-iskart-56-1961016`, a site where the copypaste hijacker can **only** be removed with `||www.15min.lt/naujiena^$inline-script` that is supposed to be in Dandelion Sprout's Annoyances List but which `exclusions.txt` is currently removing from the AdGuard-included list version.

Trust me, I've tried a whole lot of other approaches to defeat the copypaste hijacker, none of which worked.

### Proposed solution

I wish that it could be made possible for included lists to use entries with `$inline-script`, in order to handle sites and situations like those.

### Privacy

- [X] I agree to follow this condition

**Comment by Yuki2718** [comment]
For the time being you can use `$csp=script-src 'self' 'unsafe-eval' http: https:` (`$inline-script`) is more of an alias of this`. It'll be convenient tho if AG supports `$inline-script`.

**Comment by DandelionSprout** [comment]
Having only now noticed https://github.com/AdguardTeam/FiltersRegistry/pull/689, I at least presume this issue has been resolved pretty well by that.
