### ISSUE TITLE
Asking for advice on Dandelion Sprout's Annoyances List

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/FiltersRegistry#693]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

I've been thinking for some months now about adding an additional `!#include` subfile to Dandelion Sprout's Annoyances List, though it's an unusual enough topic that I figured I should ask for permission and go-ahead for it:

[Anti-'Prayer times' List](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Sensitive%20lists/AntiPrayerTimesList.txt), which aims to remove major newssites' prayer time prompts/banners, based on the assumption that such religious promotions don't belong on general newssites. For instance stuff like this (Source: `https://www.bursahabermerkezi.com/`): 
![image](https://user-images.githubusercontent.com/22780683/206175872-61f47adc-00d9-42ac-8dae-0fc81fc50e6f.png)

The file is well-maintained, and I've put in fairly heavy effort in the past 48 hours to reduce the chance of non-newssites getting false positives; and before that, I looked into having the list cover many countries where such banners tend to be on newssites (e.g. Turkey, Libya, Indonesia, Bangladesh, Kuwait, etc.). For the purposes of list inclusion and consideration, you guys can assume that its bottommost 2 paragraphs doesn't exist.

Nevertheless I figured I'd ask about it, so people wouldn't think I had gone crazy à la the "The old Finnish list blocking labour union sites" incident, and also to make sure that the AdGuard Team (who tend to be concerned about EU laws) didn't think that the fraudulent "laws" of e.g. Saudi Arabia or Pakistan would forbid the inclusion of sublists like this.

### Proposed solution

That I get the green light to include "Anti-'Prayer times' List" in "Dandelion Sprout's Annoyances List" and that people wouldn't think I'd have become crazy due to it.

### Additional information

None at the moment. I'd be open for any questions you guys would have, however.

**Comment by Alex-302** [comment]
You can do anything you want:) But I haven't noticed reports with these banners.

**Comment by ameshkov** [comment]
You'll be hiding elements that are not directly relevant to the website content so this is in line with the list name and purpose.
