### ISSUE TITLE
Change which filters are labeled "recommended" in the Annoyances group

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#718]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

Currently, the only recommended filter list in the group is the "AdGuard Annoyances filter".

Nowadays, it is divided into smaller lists and that's how it will be in the future.

### Proposed solution

Here's what we should do:
1. Label the smaller lists "recommended"
2. Remove the "recommended" label from the "AdGuard Annoyances filter"
3. Make sure that the description of the Annoyances filter correctly explains that this is just all smaller lists combined and *nothing* save for this.
4. At some (distant) point in the future we should consider removing the old annoyances list.

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uBlock-issues/issues/2217
