### ISSUE TITLE
Simplifying the description of the 10th filter

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/FiltersRegistry#733]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

As we discussed it, the filter description of the 10th one looks a bit long with detalis.
Current description - https://uploads.adguard.org/slbdzdrvwdmmh.png

### Proposed solution

I suggest to change it to something like that. @ss-orlova could you take a look at it and also do some changes if necessary?
`do some changes if necessary` it means your ideas here.
```
Filter that unblocks search ads (DuckDuckGo, Google, Bing, Yahoo) and self-promotion (discounts, promotions, etc.).
```

**Comment by slavaleleka** [comment]
current description:
https://uploads.adguard.org/slbdzdrvwdmmh.png

it was improved [almost 5 years ago](https://github.com/AdguardTeam/FiltersRegistry/commit/3ea30bbd75e0586131dc22474e4d9d3456931a8a#diff-530696e9394703290c9625954c438c8d3f498efbdd9148f948809d2850913c73R40), maybe there were some reasons to do it

**Comment by ss-orlova** [comment]
I suggest changing the description to the following
`Filter that unblocks search ads on Google, DuckDuckGo, Bing, or Yahoo and first-party ads on websites`

**Comment by Alex-302** [comment]
> first-party

use this instead

> self-promotion
