### ISSUE TITLE
exclusions have many obsolete entries

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/FiltersRegistry#753]
### Prerequisites

- [X] This problem is not related to filtering issues. Otherwise, you should read this [article](https://kb.adguard.com/technical-support/reporting-tool);
- [X] You're using an up-to-date version of the problematic filter;

### Problem description

https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/exclusions.txt looks not well-maintained and is full of obsolete entries; e.g. EasyList no more includes `||am15.net^$third-party` or `||exoclick.com^$third-party` as `$third-party` was removed from these rules.

### Proposed solution

Check all the old entries and remove or adjust accordingly.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
They can be added or exist in third-party filters.

**Comment by Yuki2718** [comment]
If `||am15.net^$third-party` needs to be excluded, shouldn't `||am15.net^` be too?

**Comment by Alex-302** [comment]
Hmm. It maybe the issue with am15.net is not actual.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/FiltersRegistry/pull/754
