### ISSUE TITLE
Inclusion request: fzListKor Filters [Language-specific]

### ISSUE THREAD

**Issue by testprogrammer2000** [AdguardTeam/FiltersRegistry#762]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

I've been observing this filter for a long time. <br/>
This filter owner is very sincere and continues to reinforce the deficiencies. <br />
Currently, advertisements on the most popular sites in South Korea are being completely blocked.<br />
Therefore, I propose the addition of fzListKor to AdGuard.<br/>

### Proposed solution

 I propose the addition of fzListKor to AdGuard. <br/> [Language-specific] <br />

### Additional information

<a href="https://raw.githubusercontent.com/elsannadisney/fzListKor/main/main.txt">https://raw.githubusercontent.com/elsannadisney/fzListKor/main/main.txt</a>

**Comment by piquark6046** [comment]
Also, It seems that the most of rules blocking advertisement is originated from YousList, EasyList, [Apious/Ads_Filter_Contents](https://github.com/Apious/Ads_Filter_Contents) [^1], List-KR filter [^2] and AdGuard filters [^2].

[^1]: The filter is literally a crap and the author performs their own sitcom.
[^2]: Some filters do not work on Unicorn Pro adblocker unlike its README.md said.

---

I found that there is invaild rule:

https://github.com/elsannadisney/fzListKor/blob/765c2d3c3c7adff5fd6015967bdabf9eb557d1bc/main.txt#LL1365-L1365C49

---

I don't know why the filter author uses the outdated method blocking PowerLink advertisement on namu.wiki.

https://github.com/elsannadisney/fzListKor/blob/765c2d3c3c7adff5fd6015967bdabf9eb557d1bc/main.txt#L353-L354

https://github.com/elsannadisney/fzListKor/blob/765c2d3c3c7adff5fd6015967bdabf9eb557d1bc/main.txt#L1367-L1369

**Comment by testprogrammer2000** [comment]
All right. I will request it again after the filter has been sufficiently improved.

**Comment by piquark6046** [comment]
Even so, there are no related category in [AdguardTeam/FiltersRegistry's filter purpose definition](https://github.com/AdguardTeam/FiltersRegistry/blob/master/groups/metadata.json).

The number of a filter's GitHub star, someone wants to register into AdguardTeam/FiltersRegistry, must be 50 or higher.

https://github.com/AdguardTeam/FiltersRegistry#what-filters-can-be-added-to-this-repository

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/FiltersRegistry/issues/762#issuecomment-1477815532 besides that, the filter should be popular.
