### ISSUE TITLE
GoatRAT Trojan block request

### ISSUE THREAD

**Issue by ViniciusFXavier** [AdguardTeam/FiltersRegistry#763]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

GoatRAT was originally created as an Android Remote Administration Tool to seize control of a victim’s device. However, a new version of GoatRAT functions as a Banking Trojan, specifically aimed at Brazilian banks.

Like other types of Banking Trojans, GoatRAT utilizes the Accessibility service to implement an Automatic Transfer System (ATS) framework, which enables the transfer of money from the victim’s account using the PIX key. The PIX key is used to perform the instant payment. This malware currently targets three Brazilian banks: NUBank, Banco Inter, and PagBank.

![image](https://user-images.githubusercontent.com/40774281/226697704-8d3874d2-43e6-4dbb-a8bb-5796352dccbf.png)

URL source: https://blog.cyble.com/2023/03/14/goatrat-android-banking-trojan-variant-targeting-brazilian-banks/

### Proposed solution

Block URL's:
<html>
<body>

URL | Description
-- | -- 
hxxps://bit[.]ly/nubankmodulo | Shortened malware distribution URL
hxxps://goatrat[.]com/apks/apk20.apk | Malware distribution URL
hxxp://api.goatrat[.]com:3008 | C&C server to receive PIX key

</body>
</html>

Block: `||goatrat.com^`

**Comment by zloyden** [comment]
In fact, it is not the right repo. You can read the purpose here https://github.com/AdguardTeam/FiltersRegistry/blob/master/README.md.
I will address it to our support team. If you find something similar and you want it blocked in the future, you can write about it to support@adguard.com.

**Comment by zloyden** [comment]
[It is blocked.](https://reports.adguard.com/en/goatrat.com/report.html)
