### ISSUE TITLE
have repeating rules

### ISSUE THREAD

**Issue by Karmylr** [AdguardTeam/FiltersRegistry#768]
### Prerequisites

- [X] This problem is not related to filtering issues. Otherwise, you should read this [article](https://kb.adguard.com/technical-support/reporting-tool);
- [X] You're using an up-to-date version of the problematic filter;

### Problem description

have repeating rules

### Proposed solution

delete repeating rules

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
@Karmylr if you find some repeated rules, you should report about it here https://github.com/AdguardTeam/AdguardFilters.
To do this: use this [link](https://reports.adguard.com/new_issue.html).
