### ISSUE TITLE
Add EasyList Portuguese Filter

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/FiltersRegistry#786]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

I've noticed that a fair few entries in [https://easylist-downloads.adblockplus.org/easylistportuguese.txt](https://easylist-downloads.adblockplus.org/easylistportuguese.txt) are not present in AdGuard Spanish/Portuguese Filter, especially ones for the `.cv`, `.ao`, and `.mz` TLDs.

Since most other AdGuard regional lists tend to incorporate ABP-affiliated regional lists, could the same be done for EasyList Portuguese?

### Proposed solution

Implement entries from EasyList Portuguese into AdGuard Spanish/Portuguese Filter.

### Additional information

EasyList Portuguese is a relatively new list, created in what I think was 2021, long after AdGuard Spanish/Portuguese Filter was created. So it's understandable that this implementation hasn't been done yet.

Additionally, EasyList Portuguese is (to the best of my knowledge) the only ABP-affiliated regional list to not be included at all in uBO nor AdGuard products, making it additionally important to make use of its entries somehow.

**Comment by zloyden** [comment]
I think that we can add it as a separated filter.
