### ISSUE TITLE
Reevaluate recommended Indonesian list

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/FiltersRegistry#788]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

The current recommended list AdBlockID includes large numbers of very broad cosmetic filters: `https://github.com/realodix/AdBlockID/blob/57f962c2aec0f16c25ea4ac76ef47000cdcbbda7/dist/adblockid.adfl.txt#L2044-L2510`. They are prone to false positive as reported in https://github.com/realodix/AdBlockID/issues/1382 (tho it's apparently non-public site, another case https://github.com/realodix/AdBlockID/issues/1331) and with such an amount can affect performance. I see size-based rules are sometimes useful, but the problems are 1. *all* generic instead of site-specific and 2. just way too many. See how many size-based generic rules other popular lists include; e.g. EasyList China: 0, EasyList Spanish: 0, Liste FR: 0, ABPindo: 0 <sup>*</sup>. The list may still worth recommended list for its effectiveness, which admittedly I don't know. But the point above is something to be considered with all other factor.

### Proposed solution

NA

____
* AG Base is the list including many such rules, but still far less and happy to trim them down.

**Comment by Yuki2718** [comment]
Yeah, there's no problem as they're moved to optional list. 
@realodix Hi, thank you for your quick fix and all the nice work, and sorry for my impatience.

**Comment by zloyden** [comment]
As I can see, it's resolved by the author of the filter.

> AdBlockID seems to be much more actively developed than ABPindo

Seems like that.
