### ISSUE TITLE
推荐两个用于中文区的过滤器

### ISSUE THREAD

**Issue by xiulou23** [AdguardTeam/FiltersRegistry#791]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

希望你们能把我推荐的两个过滤器放在Adguard过滤器列表中，你们也说过考虑添加的

### Proposed solution

Anti-AD : https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-adguard.txt
AdRules Adblock List Plus : 
https://raw.githubusercontent.com/Cats-Team/AdRules/main/adblock_plus.txt
就这两个过滤器，希望尽快加上

**Comment by Alex-302** [comment]
Also a complilation of filters.

**Comment by xiulou23** [comment]
> Also a complilation of filters.

所以你们是不想把这两个过滤器添加进去吗？

**Comment by Alex-302** [comment]
The problem with compilations is that if there is a problem, we will have difficulty informing the authors of the original filter.
