### ISSUE TITLE
建议将我推荐的过滤器添加到过滤器列表中

### ISSUE THREAD

**Issue by xiulou23** [AdguardTeam/FiltersRegistry#792]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

推荐一个广告过滤过滤器和一个保护隐私的过滤器，希望加到Adguard过滤器列表中，这两个过滤器是用于中文区的

### Proposed solution

adblock-plus ：
https://raw.githubusercontent.com/uniartisan/adblock_list/master/adblock_plus.txt

adblock-privacy ：
https://raw.githubusercontent.com/uniartisan/adblock_list/master/adblock_privacy.txt

就这两个过滤器，希望你们考虑一下添加到过滤器列表中，第二个是用于隐私的，第一个是过滤广告的，都是优秀的过滤器

**Comment by xiulou23** [comment]
上面两个过滤器的名字应该改成uniartisan's Adblock List Plus和uniartisan's Privacy List

**Comment by xiulou23** [comment]
上面的两个过滤器应该改成uniartisan's Adblock List Plus和uniartisan's Privacy List

**Comment by Alex-302** [comment]
Lookis like a compilation oа our filters and easylist.
