### ISSUE TITLE
推荐个过滤器

### ISSUE THREAD

**Issue by xiulou23** [AdguardTeam/FiltersRegistry#794]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

我要推荐的过滤器的链接是：https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockfilters.txt
你们看一下是否符合标准

### Proposed solution

这个过滤器8小时更新一次，而且规则数量多，包含了其他Adguard没有的过滤器的规则

**Comment by Alex-302** [comment]
This is a compilation of many filters.
`! Description: 适用于AdGuard的去广告合并规则，每8个小时更新一次。规则源：1Hosts (Lite)、ADgk、AdGuard Base filter、AdGuard Base filter、AdGuard DNS filter、AdRules DNS List、Hblock、NEO DEV HOST、OISD Basic、1024 hosts、ad-wars hosts、StevenBlack hosts、xinggsf、EasyList、Easylist China、EasyPrivacy、CJX's Annoyance List、SmartTV Blocklist`

We favor original filters.
