### ISSUE TITLE
polish annoyance filters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#8]
@KonoromiHimaries commented on [Thu Dec 14 2017](https://github.com/AdguardTeam/AdguardFilters/issues/8413)

Polskie filtry annoyances

this list
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/blob/master/PPB.txt

---

@Alex-302 commented on [Thu Dec 14 2017](https://github.com/AdguardTeam/AdguardFilters/issues/8413#issuecomment-351664681)

Why do you close it?)

---

@Alex-302 commented on [Thu Dec 14 2017](https://github.com/AdguardTeam/AdguardFilters/issues/8413#issuecomment-351716505)

@AdamWr could you check this filter? Is it useful?

---

@AdamWr commented on [Thu Dec 14 2017](https://github.com/AdguardTeam/AdguardFilters/issues/8413#issuecomment-351747293)

It is like AdGuard Annoyances filter, but for Polish websites, so I think it is useful.

---

@Alex-302 commented on [Thu Dec 14 2017](https://github.com/AdguardTeam/AdguardFilters/issues/8413#issuecomment-351755014)

Ok, we will add it, but a bit later.

**Comment by Alex-302** [comment]
added
