### ISSUE TITLE
Add "Threads" as a blocked service/website in AdGuard DNS Parental Control

### ISSUE THREAD

**Issue by PavelParkhomenko** [AdguardTeam/FiltersRegistry#815]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

Currently, the new social network "Threads" from Meta is not included in the "Blocked Services" list

### Proposed solution

Add "Threads" to the "Blocked Services" list in AdGuard DNS Parental Control

**Comment by zloyden** [comment]
In fact, it's not related to FiltersRegistry repo.
As I see, we have a task there about that https://github.com/AdguardTeam/HostlistsRegistry/issues/267.
