### ISSUE TITLE
Add hagezi filter

### ISSUE THREAD

**Issue by RelvinArsenio** [AdguardTeam/FiltersRegistry#819]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

I've come across a widely used blocklist known as [hagezi dns-blocklists](https://github.com/hagezi/dns-blocklists). This blocklist serves to prevent access to potentially harmful or unwanted websites. However, I couldn't find this specific filter listed in the AdGuard Filters Registry. Since this blocklist is known for its effectiveness, it would be valuable to include it in the registry.

### Proposed solution

I suggest adding the [hagezi dns-blocklists](https://github.com/hagezi/dns-blocklists) filter to the AdGuard Filters Registry. By doing so, users of AdGuard will have the option to easily integrate this powerful blocklist into their filtering setup. It could enhance the overall filtering capabilities of AdGuard and provide users with an additional layer of protection against undesirable websites.

### Additional information

The [hagezi dns-blocklists](https://github.com/hagezi/dns-blocklists) filter has gained popularity for its ability to efficiently block unwanted content. Integrating it into the AdGuard Filters Registry could contribute to a more comprehensive and versatile filtering experience for AdGuard users.

I'm excited about the potential positive impact of this addition and would love to see the [hagezi dns-blocklists](https://github.com/hagezi/dns-blocklists) filter become part of the AdGuard Filters Registry.

**Comment by piquark6046** [comment]
hagezi dns-blocklists is already registered in [AdguardTeam/HostlistsRegistry](https://github.com/AdguardTeam/HostlistsRegistry/issues/95).
Did you know that?
https://github.com/AdguardTeam/HostlistsRegistry/issues/95
