### ISSUE TITLE
Experimental Filter causing redirections when updated in uBO

### ISSUE THREAD

**Issue by uBlock-user** [AdguardTeam/FiltersRegistry#82]
Hey @ameshkov Experimental Filter doesn't update and causes redirections in the logger when I tried to update it in uBO. Just a heads up!

Link - https://filters.adtidy.org/extension/ublock/filters/5.txt

Logger redirections - 

![](https://i.gyazo.com/d686b0575765a9b240dfe6bce167df08.png)

**Comment by ameshkov** [comment]
We are testing `!#include ` and `!#if` filters directives and these should be gone soon.

**Comment by uBlock-user** [comment]
Why is it only happening to the Experimental Filter though ?

**Comment by ameshkov** [comment]
@uBlock-user we added these new directives to the Experimental filter (as per name:) ):
https://github.com/AdguardTeam/AdguardFilters/blob/master/ExperimentalFilter/sections/Other/filter.txt

**Comment by uBlock-user** [comment]
I hope you remove it soon, I had to remove the filter as it no longer updates and causing an endless loop of redirections.

**Comment by ameshkov** [comment]
Yeah, it will be removed in a couple of hours, we're almost finished.

> I hope you remove it soon, I had to remove the filter as it no longer updates and causing an endless loop of redirections.

Too bad, this looks like a uBO bug to me.

@gorhill take a look plz. `!#include ` pointing to a non-existing file seem to be messing with uBO.

* File: `https://filters.adtidy.org/extension/ublock/filters/5.txt`
* Includes `https://filters.adtidy.org/extension/ublock/filters/windows.txt` (404)
* Causes an infinite loop

**Comment by uBlock-user** [comment]
Same issue occurs if I add https://filters.adtidy.org/extension/chromium/filters/5.txt FYI

**Comment by gorhill** [comment]
> pointing to a non-existing file seems to be messing with uBO

I am not seeing this on my side, error was detected and loading was aborted. uBO will consider the fetch to have errored if one of the 3 following conditions is fulfilled:

- Status code is outside the 200-299 range; OR
- No data in the response body; OR
- First and last character of trimmed response body is `<` and `>`.

In the current case, the first condition was hit (404).

**Comment by uBlock-user** [comment]
What about the endless loop ? It tries, gets redirected, fails and then tries again repeatedly.

**Comment by gorhill** [comment]
> What about the endless loop ?

As said, I am not seeing an endless loop. If you see this it means one of the 3 mentioned conditions was not met. uBO does not "retry" a failed fetch, there is no code in uBO to do so, it aborts when it detects one.

**Comment by ameshkov** [comment]
> What about the endless loop ? It tries, gets redirected, fails and then tries again repeatedly.

We are observing it on the server side: something is constantly hitting the rate limit. Rate limited requests look like they're from ubo (random `?_=` parameter).

**Comment by uBlock-user** [comment]
> As said, I am not seeing an endless loop.

It does take a break of few secs approximately before trying again. I will post a new logger output.

**Comment by gorhill** [comment]
@ameshkov You say you also experience an infinite loop -- I am unable to reproduce this. This is where uBO starts the fetching of a list and where it handles `include` directives:

https://github.com/gorhill/uBlock/blob/master/src/js/assets.js#L227

This is called only for when a list is fetched, i.e. never repeatedly.

**Comment by gorhill** [comment]
> It does take a break of few secs approximately before trying again

Did you customized some advanced settings?

**Comment by uBlock-user** [comment]
Happened again

![](https://i.gyazo.com/cf9a540df1a12ce9ec3230d422a07bf5.png)

> Did you customized some advanced settings?

Yes, most of them.

![](https://i.gyazo.com/d48d0b2dcbc9a95c23b1866ed20f9371.png)

**Comment by uBlock-user** [comment]
and again(larger output)

![](https://i.gyazo.com/8046b01e3de80357e23b75f4af800942.png)

**Comment by gorhill** [comment]
Thanks, I can reproduce with your custom settings. Will look into it.

**Comment by uBlock-user** [comment]
I customized them a long time ago, is that the cause ?

**Comment by gorhill** [comment]
No the cause is uBO wasn't prepared to deal with multiple `!#include` sub-lists failing to be fetched. In the current case I see three sublists which fetch operation result in error. I will push a fix soon.
