### ISSUE TITLE
向你们推荐一个广告过滤器

### ISSUE THREAD

**Issue by xiulou23** [AdguardTeam/FiltersRegistry#824]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

https://raw.githubusercontent.com/hululu1068/AdGuard-Rule/main/rule/all.txt
上面就是我推荐给你们的中文过滤器，你们看一下是否能加进Adguard内置的过滤器列表中

### Proposed solution

https://raw.githubusercontent.com/hululu1068/AdGuard-Rule/main/rule/all.txt

**Comment by Alex-302** [comment]
Just a compilation on many filters, including AdGuard filters and other, included to the filters list of AdGuard.
