### ISSUE TITLE
Separate stealth exception filters from AdGuard Base filters list

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/FiltersRegistry#841]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

Currently, AdGuard uses part of AdGuard Base filters list to fix an incorrect blocking issue while AdGuard stealth option is enabled.

Due to current filters lists optimization configuration of AdGuard, a stealth exception filter can be excluded from complied one.
And, I think that purpose of the stealth exception filter and adblocking filter existing in AdGuard Base filters list are different.
Finally, a user who use AdGuard stealth option without AdGuard Base filters list and does not visit international websites [^1] for better performance may suffer.

[^1]: Including English-language websites. 

### Proposed solution

I propose new filters list that only contains stealth exception filters and remove them from AdGuard Base filters list.
Also, if a user enables the option, the filters list will be enabled automatically.

**Comment by ameshkov** [comment]
Tbh, I don't like the idea of having a separate list for fixing stealth.

> Due to current filters lists optimization configuration of AdGuard, a stealth exception filter can be excluded from complied one.

Can't we fix this instead?

**Comment by zloyden** [comment]
> Tbh, I don't like the idea of having a separate list for fixing stealth.

I agree with this.

> Can't we fix this instead?

What if we add `/notOptimized` to this file?
