### ISSUE TITLE
Add Phishing.army blocklist

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/FiltersRegistry#855]
Add https://phishing.army/download/phishing_army_blocklist_extended.txt

It updates regularly.

Main page:
https://phishing.army/

Really good filter

**Description:**
> Generated every 6 hours from [PhishTank](https://www.phishtank.com/), [OpenPhish](https://openphish.com/),
[Cert.pl](https://www.cert.pl/ostrzezenia_phishing/), [PhishFindR](https://github.com/mitchellkrogza/Phishing.Database), [Urlscan.io](https://urlscan.io/) and [Phishunt.io](https://phishunt.io/) reports.
Each domain is analyzed to eliminate false positives,
through the Whitelist of [Anudeep](https://github.com/anudeepND/whitelist) and the [Alexa Rank](https://www.alexa.com/topsites)

**Comment by zloyden** [comment]
Hi! As I see, the filter is good, but it should be oriented to the content blockers as it's said in our rules. [This repo](https://github.com/AdguardTeam/HostlistsRegistry) is more suitable for such filters.
However, if the author adds support for rules with the `$all` modifier, we can reconsider this again.

**Comment by ameshkov** [comment]
Can't we automatically convert it to make it compatible with AG?

**Comment by zloyden** [comment]
Actually, it can by using `/addModifiers`. I think we can add it in that case if you don't mind.

**Comment by ameshkov** [comment]
Yeah, why not
