### ISSUE TITLE
Increase trust level of Fanboy's Annoyance filters list

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/FiltersRegistry#867]
### Prerequisites

- [X] This problem is not related to filtering issues. Otherwise, you should read this [article](https://kb.adguard.com/technical-support/reporting-tool);
- [X] You're using an up-to-date version of the problematic filter;

### Problem description

Currently, the configuration for Fanboy's Annoyance filters list uses uBO version of the filters list.
But, the value of its trust level is `low`.

As a result, many filters using advanced filtering syntax are deleted.

Related issue: https://github.com/AdguardTeam/AdguardFilters/issues/168277

### Proposed solution

Increase trust level of Fanboy's Annoyance filters list.

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
Fail: #866
