### ISSUE TITLE
Add AlleBlockV2 continued by CrusheerPL

### ISSUE THREAD

**Issue by FadeMind** [AdguardTeam/FiltersRegistry#875]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

Initial AlleBlock was abandoned some times ago and removed from  Filters Registry. 

### Proposed solution

Please  add **AlleBlockV2** Filter List

`https://raw.githubusercontent.com/CrusheerPL/AlleBlockV2/master/AlleBlockV2.txt`

> Always fresh filter list for ABP/uBO/AdGuard hiding unnecessary & irritative elements of advertising portals from Allegro Group (Allegro, Allegro Lokalnie, MALL CZ/SK/HU/HR, mimovrste). Derived from original AlleBlock 

### Additional information

Author @CrusheerPL

**Comment by zloyden** [comment]
I don't see that the filter satisfies our criteria.
Please read the rules before creating such request next time https://github.com/AdguardTeam/FiltersRegistry#what-filters-can-be-added-to-this-repository.
