### ISSUE TITLE
remove adblock protector 2

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/FiltersRegistry#9]
@KonoromiHimaries commented on [Fri Dec 15 2017](https://github.com/AdguardTeam/AdguardFilters/issues/8458)

>AdBlock Protector 2 Canceled in favor of Nano Adblocker

https://github.com/AdBlockProtector2/AdBlockProtector2#adblock-protector-2-canceled-in-favor-of-nano-adblocker

![2017-12-15 21_47_12-ustawienia adguard](https://user-images.githubusercontent.com/5884000/34059927-9e200b0c-e1e1-11e7-8f2f-580d80d62271.png)

---

@Alex-302 commented on [Sat Dec 16 2017](https://github.com/AdguardTeam/AdguardFilters/issues/8458#issuecomment-352186190)

@ameshkov can we remove it?

---

@ameshkov commented on [Sun Dec 17 2017](https://github.com/AdguardTeam/AdguardFilters/issues/8458#issuecomment-352262843)

We can rename it or replace with another filter.

---

@ameshkov commented on [Sun Dec 17 2017](https://github.com/AdguardTeam/AdguardFilters/issues/8458#issuecomment-352262929)

Let's replace it with the Polish Annoyances filter maybe?
https://github.com/AdguardTeam/AdguardFilters/issues/8413

---

@Alex-302 commented on [Mon Dec 18 2017](https://github.com/AdguardTeam/AdguardFilters/issues/8458#issuecomment-352427529)

@ameshkov I can't change description in DB.

---

@ameshkov commented on [Tue Jan 02 2018](https://github.com/AdguardTeam/AdguardFilters/issues/8458#issuecomment-354828142)

@Alex-302 sorry for the late reply. It's not too long till you'll be able to do it manually without messing with the DB.

**Comment by Alex-302** [comment]
removed
