### ISSUE TITLE
Update homepage url for EasyList Italy and other similar filter lists

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/FiltersRegistry#901]
### Prerequisites

- [X] This problem is not related to filtering issues. Otherwise, you should read this [article](https://kb.adguard.com/technical-support/reporting-tool);
- [x] You're using an up-to-date version of the problematic filter;

### Problem description

current [EasyList Italy's homepage](https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_109_EasyListItaly/metadata.json#L6) url points to the main page — https://easylist.to/ — but the list is not mentioned there.

it is also relevant for EasyList Germany and maybe some other filter lists

### Proposed solution

it would be better to change it to
https://easylist.to/pages/other-supplementary-filter-lists-and-easylist-variants.html

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It will be changed in their repo
