### ISSUE TITLE
Remove I don't care about cookies list

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/FiltersRegistry#905]
### Prerequisites

- [X] This problem is not related to filtering issues. Otherwise, you should read this [article](https://kb.adguard.com/technical-support/reporting-tool);
- [X] You're using an up-to-date version of the problematic filter;

### Problem description

The list was sold to Avast, which made it's not easy to contact the maintainer face-to-face when problems like https://github.com/AdguardTeam/AdguardFilters/issues/172573 arose. According to @DandelionSprout the list is no more well-maintained.

### Proposed solution

Remove the list.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@kiboke Hi! Do you still maintain this filter?

**Comment by kiboke** [comment]
> @kiboke Hi! Do you still maintain this filter?

Hi @Alex-302 I don't maintain it anymore, people from GEN Digital Ltd. should do it.

**Comment by Alex-302** [comment]
@kiboke Ok, got it.
Do you know how problems can be reported to them?)

**Comment by kiboke** [comment]
Unfortunately I don't know that anymore.

**Comment by Alex-302** [comment]
We'll observe the complaints and decide whether to remove or keep them.

**Comment by DandelionSprout** [comment]
As far I've could tell in the past week or two, there remains cases where IDCAC blocks or bypasses notices, which "AdGuard Cookie Filter" either still haven't added, or which it breaks sites through. So I'd *personally* do a grace period of 1½-2 months before IDCAC could be removed, while Cookie Filter in the meantime could intensify their efforts to cover more sites (esp. non-English sites) and to heavily expand the use of generic entries.

**Comment by zloyden** [comment]
The filter has been disabled.
