### ISSUE TITLE
Remove Nocoin Filter List

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/FiltersRegistry#917]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

This is pretty much a dead list. [Last updated](https://github.com/hoshsadiq/adblock-nocoin-list/commits/master/) 6 months ago and I'm not sure whether those last updates actually made sense.

### Proposed solution

Remove the list

**Comment by zloyden** [comment]
The filter has been disabled.
