### ISSUE TITLE
Please add Energized Ultimate / Energized Unified.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/FiltersRegistry#92]
These large blocking lists are for AG for Android, not for AG for iOS v3.

https://github.com/EnergizedProtection/block

Amazing.
The combination of most my favorite filters.

Energized Ultimate (Adware and Malware Unified):
https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/filter

Energized Unified (Adware, Malware and Porn Unified):
https://raw.githubusercontent.com/EnergizedProtection/block/master/unified/formats/filter

Package Details
Energized Basic:
1Hosts.cf, AdAway, Adblock No Coin List, add.2o7Net, add.Dead, AdGuard Domains, DNS & Spyware, Ador Energized, AdZHosts, Anti-PopAds, Airelle RSK, Anudeep Adservers, Better Fyi Trackers, CK Ad & WEB RTC, Disconnect.me Ad & Malware, DShield.org LOW, Easylist & Adservers, EasyPrivacy, hBlock, hpHosts ATS, EMD to & WRZ, KADhosts, LightSwitch Extended, MalwareDomains.com - Immortal & Just Domains, MoaAB, MVPS.ORG, NeoHosts, Notracking, NSABlocklist, someonewhocares, Spam404.com - Ad, Steven Black Unified & Fakenews-Gambling, Streaming Ads, UncheckyAds, Vokins YHosts, Windows Spy Blocker, PGL YoYo.org, ZeroDot1 CoinBlockerList and Zeus Tracker

**Energized Ultimate:
Energized Basic, Adguard Safari, Adware Filters, Airelle Ads & Track, Anudeep Coinminer, Bad Boyz Hosts, Blockzilla, CK Barbblock, Cybercrime, Disconnect.me Tracking, DShield.org High & Medium, EasyPrivacy Specific, Thirdparty & Tracking, Fanboy Annoyance & Enhanced Stats, hpHosts EXP, GRM, HJK & MMT, Matomo.org Spammers, Phishing Hosts, Quidsup NoTrack, Ransomware Tracker, Sinfonietta Snuff, Spam404.com Main Blacklist, Squidblacklist DG Ad & Malicious, Stopforumspam.com and ZeroDot1 CoinBlockerList Browser & Optional**

**Energized Unified:
Energized Ultimate and Porn**

**Comment by zloyden** [comment]
I'm not sure that we have to add this to filters.
According to our rules, the filter should be oriented towards browser content blockers.
For now it's better to file an issue here https://github.com/AdguardTeam/HostlistsRegistry.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/180017569-b4e47e2e-2996-4299-9005-10a9398430c4.png)

</details><br/>
