### ISSUE TITLE
Add `phishing-filter`

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersRegistry#924]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

https://gitlab.com/malware-filter/phishing-filter

### Proposed solution

Add https://malware-filter.gitlab.io/malware-filter/phishing-filter-ag.txt
It is small, so add with `/notOptimized` This version if with `$all` modifier.

**Comment by zloyden** [comment]
The filter has been added.
