### ISSUE TITLE
Add Scam Blocklist

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersRegistry#925]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

https://github.com/durablenapkin/scamblocklist

### Proposed solution

https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt

Small, so with `/notOptimized`. **Rules don't have `$all` modifier**

**Comment by DandelionSprout** [comment]
With some exceptions, mainly for older domains, 60% of his list can be compressed into a mere 10 entries:
```
.avito.avito.avito.$all
.booking.com-id*$all
.com-id*.info^$all
||yandex.avito.sber*$all
||yandex.avito.www.$all
||yandex.pay.avito.$all
.avito.www.booking.$all
||booklng.com-*$all
||avito.avito.www.avito.$all
||booking.com-id*$all
```

**Comment by zloyden** [comment]
The filter has been added.

**Comment by Alex-302** [comment]
@durablenapkin Could you please tale a look? https://github.com/AdguardTeam/FiltersRegistry/issues/925#issuecomment-2037565989

**Comment by durablenapkin** [comment]
Thanks @Alex-302, I finally had some time to update things to incorporate @DandelionSprout's expressions to reduce the filesize significantly. Next nightly update (in ~8 hours from now) will also include `$all` appended to all entries.

I'm not sure if the `/addModifiers="all"` parameter will need to be removed from https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_256_Scam_Blocklist/template.txt (tagging @zloyden just in case)

Thanks all again!

**Comment by Alex-302** [comment]
> I'm not sure if the `/addModifiers="all"` parameter will need to be removed from

We will remove it. It has a bug - added even if a rule has modifier.

**Comment by durablenapkin** [comment]
> We will remove it. It has a bug - added even if a rule has modifier.

Sorry please keep the `/addModifiers="all"` parameter.

As pointed out/discussed in https://github.com/jarelllama/Scam-Blocklist/issues/310 for maximum compatibility with Pihole and other solutions I'll continue the list without any modifiers. My apologies for any inconvenience!

**Comment by Alex-302** [comment]
@durablenapkin Ok)
