### ISSUE TITLE
Add uBlock₀ filters – Badware risks

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/FiltersRegistry#926]
### Prerequisites

- [X] I checked the documentation and understood it;
- [X] I checked to make sure that this issue has not already been filed;

### Problem description

https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt

### Proposed solution

Add https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/badware.txt
with `/notOptimized`

Instead of `uBlock₀` use `uBlock Origin` in the meta.

**Comment by zloyden** [comment]
The filter has been added.
