### ISSUE TITLE
Do not build Online Malicious URL Blocklist for AdGuard for iOS

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/FiltersRegistry#929]
### Prerequisites

- [X] This problem is not related to filtering issues. Otherwise, you should read this [article](https://kb.adguard.com/technical-support/reporting-tool);
- [ ] You're using an up-to-date version of the problematic filter;

### Problem description

The filter is not used by AdGuard for iOS, it should not be built for that platform at all

### Proposed solution

use `platformsExcluded` to avoid filter build for specific platform

### Privacy

- [X] I agree to follow this condition

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/FiltersRegistry/pull/935#issuecomment-2039254276.
